const listSelectors = {
  Welcome: {
    deviceId: '~deviceId',
    magicLinkBaseUrl: '~magicLinkBaseUrl',
    homeScreen: '~¡Bienvenido!',
    registerButton: '~Registrarme',
    loginButton: '~Iniciar sesión',
  },
  LinkInfo: {
    acceptButton: '~Entendido',
  },
  Login: {
    homeScreen_Android: "//*[@text='1']",
    homeScreen_iOS: "~Teclado Clave Tecla 1",
    forgotMyPasscode: '~Olvidé mi clave',
    numericKeyboardNumber: '~Teclado Clave Tecla ',
    pendingAttemptsLeft: "//*[@text='Resta # intento']",
    pendingAttemptsLeftPlural: "//*[@text='Restan # intentos']",
    continueToLastAttempt: '~Aceptar',
    acceptLinkConditions: '~Boton Entendido',
    enter: '~Ingresar',
    unlinkCancel: '~Cancelar',
    unlink: '~Desvincular',
  },
  ForgotMyPasscode: {
    title: "//*[@text='Recuperar clave']",
    getItBack: "//*[@text='Recuperar']",
  },
  Biometry: {
    screenName: "//*[@text='Ingreso con biometría']",
    activateBiometry: '~Activar biometria',
    cancelBiometry: '~No por ahora',
    UpdateAndLivedABetterExperience: "//*[@text='Actualizate y viví una mejor experiencia']",
    backButton: '~VOLVER',
  },
  ActiveSession: { homeScreen: "//*[@text='Sesión activa']", finishButton: '~Finalizar' },
  AccountScreen: {
    tna: '~Taza anual remunerada',
    summaryIcon: '~resumen de gastos',
    accountSummary: '~Ver resumen de cuenta',
  },
  AccountSummaryScreen: {
    shrinkYear2021: '~Contraer listado resumenes año 2021',
    expandYear2021: '~Desplegar listado resumenes año 2020',
    shrinkYear2020: '~Contraer listado resumenes año 2020',
    expandYear2020: '~Desplegar listado resumenes año 2020',
    downloadMarchSummary: '~Descargar resumen de cuenta de marzo',
    downloadJanuarySummary: '~Descargar resumen de cuenta de febrero',
    retry: '~Reintentar',
    shareMenu: '~resolver_list',
    pdf_Android: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.RelativeLayout',
  },
  ExpenseSummary: {  
    analysis_Android: "//*[@text = 'Análisis']",
    analysis_iOS: '~Análisis',
    previousMonthArrow: '~ir al mes anterior',
    subsequentMonthArrow: '~ir al mes siguiente',
    buttonSeeMoreCategories: '~Ver más categorias',
    categories_Android: "//*[@text = 'RESUMEN']",
    categories_iOS: '~RESUMEN',
    categoriesEmpty: '~Disfruta de tu tarjeta, tus consumos aparecerán acá. Si todavía no la ténes, ¡pedila en pocos pasos!',
    errorScreen: '~Algo salió mal',
    cardEgress_Android: "//*[@text = 'Egresos']",
    cardEgress_iOS: '~Egresos',
    cardentry: '~Ingresos',
    errorScreen: '~Algo salió mal',
    retry:'~Reintentar',
    txtTransferOut_Android:"//*[@text = 'Transferencia saliente']",
    txtTransferOut_iOS:"//*[contains(@name, 'Transferencia saliente') and @visible='true' and not(contains(@name,'Tasa anual remunerada'))]/XCUIElementTypeOther/XCUIElementTypeOther",
    txtTransferIn: "//*[@text = 'Transferencia entrante']",
    txtTransferInSiniestroDestino: '//*[contains(@text, "Omar Daniel")]',
    txtTransferInSiniestroConcepto: "//*[@text = 'Siniestros de seguros']",
    txtTransferInSiniestroImporte: '//*[contains(@text, "50")]',
    txtTransferInSiniestroCuit: "//*[@text = '20414505024']",
    txtReintegroObraSocialImporte: '//*[contains(@text, "60")]',
    txtReintegroObraSocialDestino: '//*[contains(@text, "Omar Daniel")]',
    txtReintegroObraSocialConcepto: "//*[@text = 'Reintegros de obras sociales y prepagas']",
    txtReintegroObraSocialCuit: "//*[@text = '20414505024']",
    txtBienesRegistrablesImporte: '//*[contains(@text, "70")]',
    txtBienesRegistrablesDestino: '//*[contains(@text, "Omar Daniel")]',
    txtBienesRegistrablesConcepto: "//*[@text = 'Bienes registrables habitualistas']",
    txtBienesRegistrablesCuit: "//*[@text = '20414505024']",
    txtHaberesImporte: '//*[contains(@text, "80")]',
    txtTransferInHaberes: "//*[@text = 'Pago de haberes']",
    txtConceptoHaberes: "//*[@text = 'Haberes']",
    txtHaberesCuit: "//*[@text = '20414505024']",
    txtTransferInInmobiliaria: "//*[@text = 'Transferencia op. inmobiliaria']",
    txtInmobiliariaImporte: '//*[contains(@text, "90")]',
    txtInmobiliariaConcepto: "//*[@text = 'Operaciones inmobiliarias']",
    txtInmobiliariaCuit: "//*[@text = '20414505024']",
    txtVariosImporte: '//*[contains(@text, "95")]',
    txtVariosDestino: '//*[contains(@text, "Omar Daniel")]',
    txtVariosCuit: "//*[@text = '20414505024']",
    txtVariosConcepto: "//*[@text = 'Varios']",
    txtDiciembre_iOS: '~DICIEMBRE',
    txtDiciembre_Android: '~DICIEMBRE',
  },
  DeviceList: {
    homeScreen: "//*[@text='Dispositivos vinculados']",
    unlinkDeviceButton: '~Desvincular',
    cancelButton: '~Cancelar',
  },
  UnlinkSuccessSreen:{
    finishButton: '~Finalizar',
  },
  DeviceChanged: {
    homeScreen: "//*[@text='Registro iniciado']",
    helpButton: '~¿Necesitás ayuda?',
    understoodButton: '~Entendido',
  },
  TabBar: {
    homeButton_Android: '~INICIO, tab, 1 out of 5',
    homeButton_iOS: '~INICIO',
    //accountButton_Android: '~CUENTA, tab, 2 out of 5',
    //accountButton_iOS: '~CUENTA',
    transferButton_Android: '~TRANSFERENCIAS, tab, 3 out of 5',
    transferButton_iOS: '~TRANSFERENCIAS',
    cardsButton_Android: '~TARJETAS, tab, 2 out of 5',
    cardsButton_iOS: '~TARJETAS',
    paymentsButton_Android: '~PAGOS, tab, 4 out of 5',
    paymentsButton_iOS: '~PAGOS',
    moreButton_Android: '~MÁS, tab, 5 out of 5',
    moreButton_iOS: '~MÁS',
    investmentsButton_iOS: '~INVERSIONES',
    investmentsButton_Android: '~INVERSIONES',
    bntInsurance: '~Seguros',
    
  },
  TopBar:{
     closeModalButton: '~VOLVER',
     shareButton: '~COMPARTIR',
     notificationsButton: '~NOTIFICACIONES',
     helpButton: '~AYUDA',
     configButton: '~CONFIGURACION',
     notificationsConfigButton: '~CONFIGURAR NOTIFICACIONES',
     chatButton: '~CHAT',
     profileButton: '~PERFIL',
     backButton: '~VOLVER',
     unlinkButtonLoginView: '~DESVINCULAR',
     indentBackButton: '~Navigate Up',
     close: '~Cerrar',
     backButtonToHelpRegister: '~Ayuda en registro',
     HelpIconOnboarding: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView',
     //btnNavigateUp: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/android.widget.ImageButton',
     btnNavigateUp:'~Navigate Up',

},
  HomeScreenModal: {
    transferHomeButton: '~Transferir',
    favoritesTitle: '~FRECUENTES',
    agendaButton: '~Ver Agenda',
    agendaTitle: '~Agenda de Destinatarios',
    addContactCustomerList: '~Agregar\nContacto',
    cbuOrAlias: '~Ingresá un Alias o CBU',
    buttonNextContact: '~Continuar',
    buttonPreviousContact: '~Atrás',
    accountInfoModalNext: '~Continuar',
    accountInfoModalPrevious: '~Volver',
    buttonAddContactSuccessful: '~Agendar Contacto',
    agendaTitleConfirmation: '~Atrás',
    newContactToTransfer: '~A un nuevo destinatario',
    favoriteContactToTransfer: '~Monzonpologustavo',
    listContactToTransfer: '~A un contacto agendado',
    buttonViewActivities: '~Ver actividades',
    btnCrearPlazoFijo: '~Crear Plazo Fijo',
  },
  VirtualCard: {
    infoVirtualCard: '~information',
    discard:'~Descartar',
    toastErrorCard: '~Reintentar',
    activateVirtualCard: '~Activar tarjeta virtual',
    startUsingYourVirtualCard: '~Empezá a usar tu tarjeta de débito virtual',
    downedService: '~En este momento tu tarjeta virtual no esta disponible',
    retry: '~Reintentar',

  },
  DiscardVirtualCard:{
    close:'~Cerrar',
    help: '~Ayuda',
    iDontUseIt: '~No la uso',
    unsafeSite:'~La usé para hacer una compra online en un sitio inseguro',
    steal:'~Me robaron los datos de la tarjeta',
    anotherReason:'~Otro motivo',
    continue: '~Continuar',
    popUpDiscard: '~Si tenés débitos automáticos o suscripciones, asegurate de asociarlos a otra tarjeta',
    discard:'~Descartar',
    cancel: '~Cancelar',
  },
  SuccessDiscardVirtual: {
    success:'~Tarjeta virtual descartada',
    finalize: '~Finalizar',
    close: '~Cerrar',
    help: '~Ayuda',
  },
  ErrorDiscardVirtual: {
    discardError: '~No pudimos descartar tu tarjeta virtual',
    retry: '~Reintentar',
    contactUs: '~Contactanos',
    close: '~Cerrar',
    help: '~Ayuda',
  },
  HomeFirsLoginRequestsCardModal: {
    btnconfirm: '~Pedí tu tarjeta',
    btnignore: '~En otro momento',
  },
  HomeScreen: {
    home: '~Inicio banco del sol',
    screenTitle_Android: "//*[@text = 'Banco del Sol']",
    screenTitle_iOS: "//*[@name = 'Banco del Sol']",
    //screenTitle: '~Banco del Sol',
    transferShortcut: '~Transferir',
    profileButton: '~profileButton',
    profile: '~PERFIL', // TODO: pedir accessibility label
    affidavitDoesntMatch: '~¿Necesitás ayuda?',
    tna: '~Taza anual remunerada',
    loading: '~cargando saldo',
    modalTnaClose: '~Cerrar información',
    modalTnaOneStep: '~Caja de Ahorro Remunerada',
    modalTnaTwoStep: '~Rendimientos cada 30 días',
    modalTnaThreeStep: '~Tu dinero siempre disponible',
    modalTnaFourStep: '~Tasa Nominal Anual',
    recentActivity_Android: "//*[@text = 'ACTIVIDAD RECIENTE']",
    recentActivity_iOS: '~ACTIVIDAD RECIENTE',
    seeMore_Android: '~Ver más', //"//*[@text = 'Ver más']",
    seeMore_iOS: "~Ver más",
    seeActivities: '~Ver actividades',
    linkIngresarExtraerDinero: '~ingresar o extraer dinero',
    btnPagar: '~Pagar',
    btnToolEntendido: '~Entendido',
    btnInvertir: '~Invertir',
    InsuranceBanner: '~Cotizá nuestros seguros y te reintegramos un 10% por 3 meses',
    InsuranceBannerSancorAdherir: '//*[@text = "¡Adherí a débito automático tus Seguros Sancor!"]',
    txtTransferOut_Android:"//*[@text = 'Transferencia saliente']",
    txtTransferOut_iOS: "//XCUIElementTypeOther[contains(@name, 'Transferencia saliente') and not(contains(@name, 'ACTIVIDAD RECIENTE')) and not(contains(@name, 'Ver más')) and not(contains(@name, 'Transferir Invertir Pagar Recargar')) and @type='XCUIElementTypeOther' and (not(contains(@name, 'Taza anual remunerada ingresar o extraer dinero')))]/XCUIElementTypeOther[1]",

  },
  HomePagar: {
   linkPagarNuevoServicio: '~Pagar nuevo servicio',
   linkPagarProximosVencimientos: '~Pagar próximos vencimientos',
    btnRecargar: '~Recargar',
    btnPagar: '~Pagar',
  },
  HomeRecargas: {
    linkRecargarNuevoServicio: '~Recargar nuevo servicio',
  },
  CardListScreen: {
    cardListScreen: '~Tarjetas',
    getCardsError: '~getcardserror',
    blockCardButton: '~Bloquear',
    confirmBlockCardButton: '~Bloquear tarjeta',
    askReprintButton: '~Solicitar reimpresión',   
    sendButton: '~Enviar',
    finishButton: '~Finalizar',
    cardActivateButton: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[1]/android.view.View',
    cardActivateNumberTxtPosOne: '//android.widget.EditText[1]',
    cardActivateNumberTxtPosTwo: '//android.widget.EditText[2]',
    cardActivateNumberTxtPosThree: '//android.widget.EditText[3]',
    cardActivateNumberTxtPosFour: '//android.widget.EditText[4]',
    cardReprintButton: '~Reimprimir',
    cardReprintContinueButton: '~Continuar',
    cardPrintContinueButton:'~Continuar',
    cardReprintDoesNetWork_Android: '~No funciona',
    cardReprintDoesNetWork_iOS: '~No funciona No funciona',
    cardReprintCantRead_Android: '~No leo el número',
    cardReprintCantRead_iOS: '~No leo el número No leo el número',
    btnNavigateUp: '~Navigate Up',
    sendCard:'~Enviar tarjeta',
    confirmSendCard:'~Confirmar',
    physicalCardSection:'~Física',
    virtualCardSection:'~Virtual',
    physicalCardTab: '~Física',
    physicalCardSecondTab: '//*[@index="1" and @content-desc="Física"]',
    activateCard :'~Activar tarjeta',
    btnNuevaDireccion :'~Ingresar nueva dirección',
    txtCalle : '~Calle',
    txtNro :'~Número',
    txtCodigoPostal :'~Código postal',
    btnListProvincia : '~Provincia',
    btnProvincia : '~Combo Provincias Buenos Aires',
    btnListLocalidad : '~Localidad',
    btnLocalidad : '~Combo Localidad 11 DE SEPTIEMBRE',
    txtTelefono : '~Teléfono',
    btnDomicilioReal : '~Este es mi domicilio real',    
    btnContinuar: '~Continuar',
    txtConfirmarDatos : "//*[@text = 'Confirmar envío']",
    txtConfirmarCalleAltura : "//*[@text = '145684, 2136,']",
    txtConfirmarProvincia : "//*[@text = '11 DE SEPTIEMBRE, Buenos Aires, 1824']",
    txtConfirmarTelefono : "//*[@text = 'Teléfono: +541532534953']",
    btnConfirmarEnvio : '~Confirmar',
    txtTarjetaAprobada : "//*[@text = 'Tarjeta aprobada']",
    btnTarjetaFisica : '~Física',
    btnActivarTarjeta : '~Activar tarjeta',
    btnPausarTarjeta: '~Pausar',
    btnReactivarTarjeta: '~Reactivar',
    btnElijoDireccion: '~145684 2136,  11 DE SEPTIEMBRE',
    bntTracking: '~Seguimiento del envío'
  },
  ContactListFlow: {
  aliasCbuField_Android: '~campo de texto',
  aliasCbuField_iOS: '~Ingresá un Alias o CBU campo de texto',
  confirmButton_Android: '~Continuar',
  confirmButton_iOS: './/*[@type="XCUIElementTypeOther"]//*[@name="Continuar"]//*[@visible="true"]',
  modalConfirmButton: '~Continuar',
  confirmNewContactButton: '~Agendar contacto',
  successContactButton: '~Finalizar',
  newContactName: '~GABRIEL ADRIAN NICORA',
  deleteContactButton: '~Eliminar contacto',
  deleteContactModalButton: '~Eliminar',
  },
  EmailSent: {
    resend: '~Reenviar',
    title: '~Te enviamos un email. Seguí las instrucciones.',
    helpButton_Android: '//*[@text="¿Necesitás ayuda?"]',
    helpButton_iOS: '~Boton Ayuda',
  },
  EmailValidation: {
    continueButton: '~Continuar',
    inputEmail_Android: '//android.widget.EditText',
    inputEmail_iOS: './/*[@type="XCUIElementTypeOther"]//*[@name="Email"]//*[@visible="true"]',
    invalidEmail: "//*[@text='Correo inválido, intentá nuevamente.']",
  },

  EmailManualLogin: {
    inputEmail_Android: '//android.widget.EditText',
    inputEmail_iOS: '//XCUIElementTypeTextField',
    continueButton: '~accessibilityLabel.continueButton',
    invalidEmail: "//*[@text='Correo inválido, intentá nuevamente.']",
  },
  EmailVerificationSent: {
    emailSent: "//*[@text='TE ENVIAMOS UN EMAIL A:']",
    resendButton: "//*[@text='Reenviar correo']",
    textNeedHelp_Android: "//*[@text='¿Necesitás ayuda?']",
    textNeedHelp_iOS: "~Boton Ayuda",
  },
  LinkedDevicesLimitReached: {
    devices: '~Ver dispositivos',
    cancel: '~Cancelar',
    unlink: '~Desvincular',
    devicePos1_Android: "//*[@text='modelo 0']",
    devicePos1_iOS: "//*[@value='modelo 0']",    
  },
  ResetPasscodeCompleted: {
    passcodeCreated: "//*[@text='Creaste tu clave']",
    finishButton: '~Finalizar',
    linkDevice: '~Vincular dispositivo',
  },
  SwornDeclarationScreen: {
    //pep: '~Toggle PEP',
    //obligatedSubject: '~Toggle Sujeto Obligado',
    //fatca: '~Toggle FATCA',
    obligatedSubject_Android: '//android.view.ViewGroup[@content-desc="Sujeto Obligado"]/android.view.ViewGroup/android.view.ViewGroup',
    pep_Android: '//android.view.ViewGroup[@content-desc="Persona Expuesta Políticamente"]/android.view.ViewGroup/android.view.ViewGroup',
    fatca_Android: '//android.view.ViewGroup[@content-desc="FATCA/CRS"]/android.view.ViewGroup/android.view.ViewGroup',
    confirm: '~Confirmar',
    loading: "//*[@text='Aguardá un instante']",
    ocupationCombo: '~Combo Provincia',
    obligatedSubjectOcupation: '~ Compraventa de divisas',
    obligatedSubjectContinue: '~Boton Continuar',
    pepContinue: '~Boton Continuar',
    setPepMe: '~Boton Yo',
    setPepRelative: '~Boton Familiar',
    setPepAcquaintance: '~Boton Allegado',
    pepRelativeCombo: '~Combo Familiar',
    pepAcquaintanceCombo: '~Combo Allegado',
    pepStillInChargeNo: '~Boton No',
    pepStillInChargeYes: '~Boton Si',
    pepChargeInput: '~Input Cargo',
    iDoNotApply: '//android.view.ViewGroup[@content-desc="accessibilityLabel.fatcaToggle"]/android.view.ViewGroup/android.view.ViewGroup',
  },
  //Pantallas de restricciones
  AccountCreationFailedScreen: {
    title: "//*[@text='Algo ocurrió con el alta de tu cuenta']",
  },
  ProcessingOnboardingData: {
    title: "//*[@text='Algo ocurrió al validar tus datos']",
    subtitle: "//*[@text='Para operar deberás comunicarte con nuestro Centro de Ayuda.']",
    tryLaterButton: '~Ingresar más tarde',
    helpButton: '~Centro de Ayuda',
  },
  AffidavitDoesNotMatchScreen: {
    title: "//*[@text='Algo ocurrió con tu Declaración Jurada']",
  },
  ProcessingOnboardingDataScreen: {
    title: "//*[@text='Algo ocurrió al validar tus datos']",
    subtitle: "//*[@text='Esto puede llevar unos minutos. Volvé a ingresar más tarde.']",
  },
  AccessRestrictionScreen: {
    title: "//*[@text='Estamos trabajando para mejorar tu experiencia']",
  },
  CneInfoScreen: {
    title: "//*[@text='¿Ya completaste el Censo Nacional Económico?']",
    iAlreadyCompletedIt: "//*[@text='Ya lo completé']",
    understood: "//*[@text='Entendido']",
    return: '~VOLVER',
  },
  restrictionFailure: {
    title: "//*[@text='Estamos validando tus datos']",
    understood: "//*[@text='Entendido']",
  },
  CompleteYourProfile: {
    title: "//*[@text='Completá tu perfil']",
    start: "//*[@text='Comenzar']",
    return: '~VOLVER',
  },
  

  //Pantallas de restricciones 
  AccountCreationFailed: {
    title: "//*[@text='Algo ocurrió con el alta de tu cuenta']",
    subtitle: "//*[@text='No es posible mostrar la información de tus productos. Comunicate con el Centro de Ayuda.']",
    tryLaterButton: '~Ingresar más tarde',
    helpButton: '~Centro de Ayuda',
  },
  FaceMatchLimitError: {
    title: "//*[@text='Lo sentimos']",
    subtitle:
      "//*[@text='Intentaste varias veces y no pudimos validarte. Para poder ayudarte, contactate con nosotros.']",
    helpLink: '~Centro de Ayuda',
  },
  TermsAndConditionsUpdated: {
    acceptTermsAndConditions: '~Aceptar',
    termsAndConditionsLink: '~Términos y Condiciones',
    privacyPolicyLink: '~Política de Privacidad',
    termsAndConditionsCheck: '~Check Box Container',
  },
  TermsAndConditions: {
    acceptTermsAndConditions: '~Continuar',
    termsAndConditionsLink: '~Términos y Condiciones',
    privacyPolicyLink: '~Política de Privacidad',
    termsAndConditionsCheck: "//*[@text='Leí y acepto los Términos y Condiciones y la Política de Privacidad.']",
  },
  CreatePasscodeCompleted: {
    loginButton: '~Ingresar',
  },
  WhitelistScreen: {
    dniInput: '~campo de texto',
  },
  NewTransferConfirmation:{
  btnTransactionConcept:'~Cambiar',
  addNote:'~editar',
  btnConceptoSiniestro: '~Siniestro de seguros botón',
  btnConceptoReintegroObraSocial: '~Reint. de O. S. y Prepagas botón',
  btnConceptoBienesRegistrables: '~Bienes Reg. Hab. botón',
  btnConceptoHaberes: '~Haberes botón',
  btnInmobiliaria: '~Op. Inmb botón',
  btnVarios: '~Varios botón',
  btnPrestamo: '~Prestamos botón',
  
  

  },
  ModalOwnership: {
    transfersHome: '~TransferHome',
    buttonMore: '~Más acciones',
    shortcutButtonAdd: '~Agregar Contacto',
    shortcutButtonSet: '~Editar Favoritos',
    shortcutButtonNewTransfer: '~Nueva Transferencia',
    modaltransferButton: "~Nueva transferencia",
    modalAddContactButton: '~Agregar contacto',
    cbuOrAlias: '~Ingresá un Alias o CBU',
   // cbuOrAlias: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.widget.EditText',
    buttonNextContact: '~Continuar',
    transfersNameAccountInfoModal: '~CUENTA A NOMBRE DE',
    transfersCuitAccountInfoModal: '~cuit',
    transfersCbuAccountInfoModal: '~cbu',
    transfersCapAccountInfoModal: '~Caja de Ahorro en pesos',
    transfersNextbuttonAccountInfoModal: '~Continuar',
    transfersReturnbuttonAccountInfoModal: '~Volver',
    customerAddContact: '~Agendar',
    transfersNewContactSuccess: '~Finalizar',
    agendaContactList: '~Ver Agenda',
    customerContactList: '~Contactos',
  },
  BlockedAccount: {
    unlockButton: '~Desbloquear',
  },
  ResetPasscodeEmail: {
    continueButton: '~Continuar',
    emailInput: '~accessibilityLabel.emailLabel',
  },
  ResetPasscodeEmailSent: {
    title: "//*[@text='TE ENVIAMOS UN EMAIL A:']",
  },
  RecoverYourPassword: {
    sendLink: "//*[@text='Enviar link']",
  },

  ProfileConfigScreen: {
    title: "//*[@text='Configuración']",
    changePasscode: "//*[@text='Cambiar clave numérica']",
    unlinkDevice: "//*[@text='Desvincular dispositivo']",
    closeAccount: "//*[@text='Dar de baja mi cuenta en Banco del Sol']",
    closeAccountPrompt: '~Darme de baja',
    closeAccountConfirm: '~Confirmar baja',
    closeAccountNotForNow: "//*[@text='Cancelar']",
    closeAccountFinalize: "//*[@text='Confirmar']",
    unsubscribeRequestIsAlreadyInProcess: "//*[@text='Tu solicitud de baja ya está en proceso']",
    unsubscribeRequestIsAlreadyInProcessFinalize: "//*[@text='Finalizar']",
    changePasscodeValidate: "//*[@text='Creá tu nueva clave']",
    changePasscodeConfirm: "//*[@text='Confirmá tu clave']",
    changePasscodeFinalize: "//*[@text='Finalizar']",
    confirmUnlink: "//*[@text='Desvincular']",
    firstDevice: "//*[@text='Este dispositivo']",
    secondDevice: "//*[@text='Este dispositivo']",
    finishUnlink: "//*[@text='Finalizar']",
    passcodeInvalidIndicator: 'ValidationIndicator', // VER IMPLEMENTACION
    config: '~CONFIGURACION',
    backButton: '~Navigate Up',
    theyOfferMeFewProducts: "//*[@text='Me ofrecen pocos productos']",
  },
  ConfigPasscodeChange: {
    title: "//*[@text='Ingresá tu clave actual']",
    backButton: '~Navigate Up',
  },
  ConfigPasscodeNew: {
    title: "//*[@text='Creá tu nueva clave']",
    backButton: '~Navigate Up',
  },
  ConfigPasscodeConfirm: {
    title: "//*[@text='Confirmá tu clave']",
    backButton: '~Navigate Up',
    passcodeDoesNotMatch: "//*[@text='La clave ingresada no coincide']",
  },
  ValidateIdentityPhotoInfo: {
    title: "//*[@text='Vamos a sacarte una foto']",
    understoodButton: '~Boton Entendido',
  },
  ProfileScreen: {
    signOff: '~Boton cerrar sesión',
    editPersonalData: '~Boton editar datos personales',
    maritalStatusBegin: '~Comenzar',
    maritalStatusCombo: '~campo de texto',
    maritalStatus: '~Combo Estado ',
    endMaritalStatus: '~Boton Terminar',
    config: 'android.widget.TextView', // TODO pedir accessibility label
    btnVerCbu: '~Ver constancia de CBU',
    btnEditarAlias: '//*[@text="Editar"]',
    txtAliasNuevo: '~campo de texto',
    btnCambiarAlias: '~Cambiar Alias',    
    txtEditarOk: '//*[@text="Ya podés compartirlo con tus contactos para que te transfieran dinero más fácil."]',
    btnFinalizarAlias: '~Finalizar',

  },
  MaritalStatus: { finishButton: '~Boton Terminar' },
  MaritalStatusCombo: { comboItem: '~Combo Estado {{itemName}}' },
  CompleteProfileInfo: { startButton: '~Comenzar' },
  SplashScreen: {
    splash: '~splash',
  },
  TransferHome: {
    buttonNotaEditar_Android: '//*[@text="Editar"]',
    buttonNotaEditar_iOS: '//*[@name="Editar"]',
    inputNota_Android: '~campo de texto',
    inputNota_iOS: '(//XCUIElementTypeOther[@name="Nota campo de texto Guardar 0  / 12"])[9]',
    buttonGuardar_Android: '~Guardar',
    buttonGuardar_iOS: '(//XCUIElementTypeOther[contains(@name,"Nota campo de texto")])[5]',
    transfersHome: '~TransferHome',
    transferHomeButton: '~Nueva Transferencia',
    agendaContactList: '~Agenda de Destinatarios',
    historyTransferTransaction: '~Historial de transferencias',
    emptyAgenda: '~Agendá a tus contactos para transferirles efectivo cuando quieras',
    emptyHistory: '~Acá vas a encontrar las transferencias que realices con tu cuenta.',
    emptyAgendaError: '~Tu agenda no esta disponible',
    emptyHistoryError: '~Tu historial no está disponible.',
    emptyTransferError: '~Tus transferencias no están disponibles',
    cbuRequest: '~Transferir',
    inputCbuOrAlias_Android: '~Ingresá un CBU, CVU o alias',
    inputCbuOrAlias_iOS: './/XCUIElementTypeTextField[@name="Ingresá un CBU, CVU o alias"]',
    buttonCbuNext: '~Continuar',
    buttonCbuPrevious: '~Atrás',
    amountRequest: '~Monto de transferencia',
    amountTransfer_Android: '//*[@text="$ 0"]',
    amountTransfer_iOS: '~Ingresar monto',
    buttonAmountRequestNext: '~Continuar',
    buttonAmountRequentPrevious: '~Atrás',
    transfersAccountInfoModalNext_Android: '~Continuar',
    transfersAccountInfoModalNext_iOS: "(//*[@type='XCUIElementTypeOther' and @name='Continuar' and @visible='true'])",
    transfersAccountInfoModalPrevious_Android: '~VOLVER',
    transfersAccountInfoModalPrevious_iOS: '(//XCUIElementTypeOther[@name="VOLVER"]',
    confirmationTransfers_Android: '~Transferir',
    confirmationTransfers_iOS: './/*[@type="XCUIElementTypeOther"]//*[@type="XCUIElementTypeOther"]//*[@type="XCUIElementTypeOther"]//*[@name="Transferir"]',
    buttonTransfersConfirmationReturn: '~Atrás',
    buttonTransfersSuccess: '~Finalizar',
    favoriteContactList: '~Contacto Favorito',
    transferTransactions: '~Movimientos',
    emptyTransferErrorTransaction: '~Lo sentimos, No es posible realizar la transferencia en este momento',
    closeEmptyTransferErrorTransaction: '~Finalizar',
    tabVouchers:'~ver comprobantes',
    tabAgenda: '~ver agenda',
    transferButtonOnContact_Android: '~Transferir',
    transferButtonOnContact_iOS: '(//XCUIElementTypeOther[@name="Transferir"])',
    understood:'~Entendido',
    txtDescripcionBanco:'~BBVA FRANCES',
    txtDescripcionBancoSol:'~BANCO DEL SOL',
    txtDescripcionMercadoPago:'~MERCADO PAGO',
    txtCVU:'//*[contains(@text, "CVU")]',
    txtCVUDestino:'//*[@text="CVU DESTINO"]',
    txtDescripcionCBU_Android:'//*[@text="0170099220000067527899"]',
    txtDescripcionCBU_iOS:'//*[contains(@name,"0170099220000067527899")]',
    txtDescripcionCVU_Android:'//*[@text="0000003100082380741030"]',
    txtDescripcionCVU_iOS:'//*[contains(@name,"0000003100082380741030")]',
    txtDescripcionContacto:'~TIA GABY',
    txtDescripcionCuenta:'//*[@text="Bbva Frances"]',
    txtDescripcionCvuGuardado_Android:'//*[@text="0000003100082380741030"]',
    txtDescripcionCvuGuardado_iOS:'//*[@name="0000003100082380741030"]',    
    txtDescripcionCbuGuardado_Android:'//*[@text="3108100900012000000522"]',
    txtDescripcionCbuGuardado_iOS:'//*[@name="3108100900012000000522"]',
    txtDescripcionCvuGuardado_Android:'//*[@text="0000003100082380741030"]',
    txtDescripcionCvuGuardado_iOS:'//*[@name="0000003100082380741030"]',   
    txtDescripcionContactoGuardado:'~JUAN CLAUDIO ORTEGA COR',
    txtDescripcionContactoGuardadoCvu:'~LEANDRO ALESSANDRELLO',
    txtDescripcionCuentaGuardadoCvu_Android:'//*[@text="Mercado Pago"]',
    txtDescripcionCuentaGuardadoCvu_iOS:'(//XCUIElementTypeOther[@name="LEANDRO ALESSANDRELLO"])[3]',    
    txtDescripcionCuentaGuardado_Android:'//*[@text="Banco Del Sol"]',
    txtDescripcionCuentaGuardado_iOS:'(//XCUIElementTypeOther[@name="JUAN CLAUDIO ORTEGA COR"])[3]',
    txtTransfereciaOk_Android:'//*[contains(@text, "realizada")]',
    txtTransfereciaOk_iOS:'//*[contains(@name, "realizada")]',
    btnVolver:'~Navigate Up',
    txtNotificacionOk: '~¡Transferencia realizada! Tu transferencia de $1.00 se realizó con éxito. hace unos segundos',
    txtNotificacionNotOk:'~La transferencia no se realizó Hubo un error al procesar tu transferencia, volvé a intentarlo. hace unos segundos',
    txtNotificacionPushOk: '//*[@text="¡Transferencia realizada!"]',
    txtNotificacionPushNotOk: '//*[@text="La transferencia no se realizó"]',
    btnVoucherVolver:'~VOLVER',
    txtSaldoCuenta_Android: '//*[contains(@text, "Saldo")]',
    txtSaldoCuenta_iOS: "//*[@type='XCUIElementTypeOther' and contains(@name, 'Caja de Ahorro en Pesos Saldo: $') and not(contains(@name,'FERNANDO DANIEL FREZZOTTI')) and not(contains(@name,'JUAN CLAUDIO ORTEGA COR'))]",
    btnComprobantes: '//*[@text="COMPROBANTES"]',
    txtComprobanteCvuTransfer: '//*[contains(@text, "1")]',
    txtComprobanteCBuTransfer: '//*[contains(@text, "95")]',
  },
  TransferSuccessScreen:{
    seeVoucher: "~Ver comprobante",
  },

  // ------------INICIO Sección de PAGOS--------------
  PaymentsHome: {
    moreActions: '~Mas acciones',
    searchNewService: '~Buscar nuevo servicio',
    tabHistory: '~pestaña historial',
    optAgenda: '~Ir a agenda',
    btnRecargaSUBE: '~Recargar SubeRecarga',
    linkPagarVariosServicios: '~Pagar varios servicios',
    btnRecargaSUBE2: 'Recargar SubeRecarga2',
    btnCajaAhorro: '~Conocé los beneficios de dejar el dinero en tu cuenta',
    btnScan: '~Escaneá el código de tus facturas y pagá más fácil',
  },
  Agenda: {
    btnNewAgenda: '~Agendar nuevo servicio',
    searchBarAgenda: '~Buscar servicio agendado',
    btnEliminarAgendaSwipe: '//*[contains(@content-desc, "Olvidar el servicio")]',
    btnCancelarEliminacion: '~Cancelar',
    btnPagarServicio: '~Pagar servicio',
    btnOlvidarEdenor: '~Olvidar el servicio EdenorConFactNoEditable Edenor',
    btnAgendarNuevo:'Agendar nuevo servicio',
  },

  
  History: {
    servDonaciones: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]',
    btnAdjuntar: '~Adjuntar',
    optCamara: '~camara',
    optGaleria: '~galeria',
    optDocumentos: '~documentos',
    clipAttachmentDonaciones: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ImageView',
    toolTipEntendido: '~entendido tooltip historial',
    lblMedioDePago: '//*[@text="MEDIO DE PAGO:"]',
    lblIdMedio: '//*[@text="1000000678"]',
    lblNroCliente: '//*[@text="Nº DE CLIENTE:"]',
    lblIdCliente: '//*[@text="6061268061710541"]',
    lblNroTransaccion: '//*[@text="Nº DE TRANSACCIÓN:"]',
    lblIdTransaccion: '//*[@text="4810"]',
    lblNroControl: '//*[@text="Nº DE CONTROL:"]',
    lblIdControl: '//*[@text="6215"]',
  },
  PaymentDetails: {
    btnCompartir: '~Compartir comprobante',
    btnAdjuntar: '~ADJUNTAR',
    btnCerrar: '~VOLVER',
    toolTipBox: '~tooltip adjuntar factura',
    toolTipEntendido: '//*[contains(@text, "Entendido")]',
  },
  ShareVoucher: {
    optComprobante: '~comprobante de pago',
    optFactura: '~factura adjunta',
    checkComprobante: '//android.view.ViewGroup[@content-desc="comprobante de pago"]/android.view.ViewGroup/android.view.ViewGroup/android.widget.ImageView',
    checkFactura: '//android.view.ViewGroup[@content-desc="factura adjunta"]/android.view.ViewGroup/android.view.ViewGroup/android.widget.ImageView',
    btnCompartir: '~compartir',
  },
  Attachment: {
    folderDownloads: '//*[@text="Download"]',
    photo: '//*[contains(@content-desc, "Photo taken on")]',
    btnConfirmar: '~confirmar',
    btnConfEliminar: '~Confirmar',
    btnEliminar: '~ELIMINAR',
    anyPDF: '//*[contains(@text, ".pdf")]',
    pdfAdjunto: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.RelativeLayout',
  },
  SearchNewService: {
    searchBar: '~Buscar empresa',
    lblPagos: '//*[@text="PAGOS"]',
    lblRecargas: '//*[@text="Recargas"]',
    servicioEdenorFactNoEditable: '//*[contains(@content-desc, "EdenorConFactNoEditable")]',
    servicioMulta140EditableAny: '//*[contains(@content-desc, "Multa140EditableAny")]',
    servicioAnticipoEditableHigh: '//*[contains(@content-desc, "AnticipoEditableHigh")]',
    servicioMedcar: '//*[contains(@content-desc, "Medcar")]',
    servicioVisa: '//*[contains(@content-desc, "empresa Visa")]',
    servicioAct0642019: '~empresa Act.06hs hasta 4/2019 del rubro Servicio Domestico Activo',
    servicioMonotrAut: '//*[contains(@content-desc, "Monotr. Aut. Activo")]',
    servicioVep: '//*[contains(@content-desc, "empresa VEP")]',
    tarjetaVISA: '~Visa',
    txtTarjetaVISA: '//*[@text="Visa"]',
    visaConFact: '~VisaConFact Visa',
    visaSinFact: '~VisaSinFact Visa',
    edenorSinFact: '~EdenorSinFact Edenor',
    servicioEdenorFactNoEditable: '~EdenorConFactNoEditable Edenor',
    servicioMulta140EditableAny: '~Multa140EditableAny Multa 140',
    servicioAnticipoEditableHigh: '~AnticipoEditableHigh Anticipo (Gcia.)',
    servicioMedcarNoFact: '~MedcarNoFact Medcar',
    inputCardNumber: '~Ingresa el codigo de pago',
    numeroTarjetaImagen: '~numero de tarjeta imagen',
    numeroTarjetaInput: '//android.view.ViewGroup[@content-desc="Ingresa el codigo de pago"]/android.view.ViewGroup/android.widget.TextView',
    tarjetaSUBE: '~empresa SUBE del rubro Transporte',
    tarjetaMasterCard: '//*[contains(@content-desc, "MasterCard")]',
    tarjetaAMEX: '//*[contains(@content-desc, "American Express")]',
    tarjetaNaranja: '//*[contains(@content-desc, "Tarjeta Naranja")]',
    btnEntendido: '~Entendido',
    servicioAnticGanancias: '~empresa Anticipo (Gcia.) del rubro Ant. Gcia. Min.',
    multa140: '~empresa Multa 140 del rubro Telefonia',
    medcar: '~empresa Medcar del rubro Medicina Prepaga',
    servicioEdenor: '~empresa Edenor del rubro Electricidad',
    searchPays: '~Buscar pagos efectuados',
    servicioMonotr: '~empresa Monotr. Aut. Activo del rubro Monotributo',
    servicioAct06hsHasta42019: '~empresa Act.06hs hasta 4/2019 del rubro Servicio Domestico Activo',
    servicioVep: '~empresa VEP del rubro Impuestos AFIP (VEP)',
    },
  Payments: {
    inputCardNumber: '~Ingresa el codigo de pago',
    numeroTarjetaImagen: '~numero de tarjeta imagen',
    numeroTarjetaInput: '//android.view.ViewGroup[@content-desc="Ingresa el codigo de pago"]/android.view.ViewGroup/android.widget.TextView',
    btnEntendido: '~Entendido',
    inputPayNumber: '~Ingresa el codigo de pago',
    continueButton: '~Continuar',
    payButton: '~Pagar',
    finishButton: '~Finalizar',
    txtMontoAPagar: '~Ingresa el monto a pagar',
    toggleAgendarServicio: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/android.view.ViewGroup',
    btnAgendar: '~Agendar servicio',
    btnGuardarServicio: '~Guardar servicio',
    linkEditarEtiqueta: '~Editar etiqueta',
    btnGuardarNuevoAlias: '~Guardar nuevo alias de servicio',
    txtCampoAlias: '~campo de texto',
    btnEditarEtiquetaDetalles: '~Editar',
    btnEliminarAgendado: '~Eliminar',
    btnConfirmarEliminacion: '~Olvidar este servicio',
    btnAgendarServicio: '~Guardar servicio',
    lblCajadeAhorro: '//*[contains(@content-desc, "caja de ahorro")]',
    btnPagoEspontaneo: '~Pago espontáneo',
    btnEfectuar: '~Efectuar',
    btnSeleccionarVencimientoMensual: '~Edenor 24/12/19 212.31',
    btnSeleccionarVencimientoAnual: '~Edenor - Cuota Anual04/12/19 10055.00',
    linkSeleccionarTodos: '~Seleccionar todos',
    btnNuevoPago: '~nuevo pago',
    lblVasAPagar0: '~Vas a pagar 0 pesos',
    lblVasAPagar10011: '~Vas a pagar 10011 pesos',
    lblVasAPagar20066: '~Vas a pagar 20066 pesos',
    lblVasAPagar30121: '~Vas a pagar 30121 pesos',
    lblVasAPagar90451: '~Vas a pagar 90451 pesos',
    checkboxPagoMasivoEdenor: '~EdenorConFactNoEditable con vencimiento el 04/12/21 por un monto de 10011',
    checkboxPagoMasivoAnticipo: '~AnticipoEditableHigh con vencimiento el 04/12/21 por un monto de 10055',
    checkboxPagoMasivoMulta: '~Multa140EditableAny con vencimiento el 04/12/21 por un monto de 10055',
    lbl2ServiciosSeleccionados: '~2 seleccionados',
    btnRecarga150: '~Recargar 150',
    btnDonacionesUnicef: '~Donaciones UNICEF de 25.00 pagado el 2017-11-10T14:39:40.271+00:00',
    btnSubeRecarga: '~SubeRecarga SUBE de 25.00 pagado el 2019-02-11T14:44:40.271+00:00',
    btnSubeRecarga2: '~SubeRecarga2 SUBE de 25.00 pagado el 2019-02-11T14:44:40.271+00:00',
    lblAlgoSalioMal: '~titulo mensaje de error',
    lblNoEsPosibleAcceder: '~bajada mensaje de error',
    btnVisa31: '~Visa 31/05/19 990.00',
    btnContinuarServNoAgend: '//*[contains(@content-desc, "Continuar")]',
    lblNosePudoAbonar: '~Edenor no se pudo abonar correctamente',
    lblAlgunosNoSePudieronAbonar: '~Algunos servicios no se pudieron abonar correctamente',
    btnPagarServicio: '~Pagar servicio',
    lblcardVisa31: '~Visa 31/05/19 990.00',
    cardVisa31: '~Visa 31/05/19 990.00',
    emptyState: '~accessibilityLabel.emptyStateText',
    bannerScan: '~Escaneá el código de tus facturas y pagá más fácil',
    bannerGenera: '~Conocé los beneficios de dejar el dinero en tu cuenta',
    btnVolverScan: '~VOLVER',
    txtUbicaScan: '//*[@text="Ubicá el código de barras donde indica la imagen"]',
    btnBuscarEmpresaScan: '~Buscar Empresa',
    lblBuscaTusServicios: '//*[@text="Buscá tus servicios e impuestos y realizá pagos y recargas cuando quieras."]',
    lblVencimientoEdenor: '~EdenorConFactNoEditable con vencimiento el 04/12/21 por un monto de 10055',
    lblVencimientoEdenorSinFact: '~EdenorSinFact con vencimiento el 04/12/21 por un monto de 10055',
    lblVencimiento04122110011: '~EdenorConFactNoEditable con vencimiento el 04/12/21 por un monto de 10011',
    lblVencimientoVisa: '~VisaConFact con vencimiento el 04/12/21 por un monto de 10055',
    btnEfectuarPagoEspontaneo: '~Efectuar un pago espontáneo',
  },

  AccountMoney: {
    tabIngresar: '~ingresar dinero',
    tabExtraer: '~extraer dinero',
    btnCopiarCBU: '~copiar cbu',
    btnCopiarAlias: '~copiar alias',
    btnCompartir: '~compartir datos',
    lblBanelco: '~banelco',
    lblRedLink: '~redLink',
    lblRapipago: '~Rapipago',
  },

  // ------------FIN Sección de PAGOS--------------
  

  // ----------INICIO Sección PRESTAMOS------------

  Prestamos: {
    btnPrestamos: '~Préstamos',
    btnContinuar: '~Continuar',
    btnSimular: '~Simular préstamo',
    lblError: '~No pudimos obtener una oferta en este momento',
    btnReintentar: '~Reintentar',
    lblPorElMomento: '~Por el momento no tenemos una oferta disponible',
    btnEntendido: '~Entendido',
    lblAprobado: '~Pedí hasta',
    btnSolicitarPrestamo: '~Solicitar préstamo',
    lblTenemosBeneficios: '~Tenemos beneficios para los empleados del Grupo',
    btnContactanos: '~Contactanos',
    lblNoPudimos: '~No pudimos obtener una oferta en este momento',
    lblRevisa: '~Revisá los requisitos para adquirir un préstamo',
    btnVerRequisitos: '~Ver requisitos',
    lblTenesUnPrestamo: '~Tenés un préstamo vigente con Banco del Sol',
    lblTenesUnaDeuda: '~Tenemos registrada una deuda con Banco del Sol',
    lblPedi: '~Pedí hasta $ 494.000 y te lo acreditamos en el momento',
    lblMisPrestamos: '//*[@text="MIS PRÉSTAMOS"]',
    lblPrestamoPersonal: '//*[@text="Préstamo Personal"]',
    lblIdPrestamo: '//*[@text="ID DE PRÉSTAMO"]',
    lblInicioPrestamo: '//*[@text="INICIO DEL PRÉSTAMO"]',
    lblFinalizacionPrestamo: '//*[@text="FINALIZACIÓN DEL PRÉSTAMO"]',
    lblDetallePagos: '//*[@text="DETALLE DE PAGOS"]',
    lblPlazo: '//*[@text="PLAZO"]',
    lblMontoCuotas: '//*[@text="MONTO DE CUOTAS"]',
    lblFechaPago: '//*[@text="FECHA DE PAGO"]',
    btnDetalleCuotas: '~Ver detalle de cuotas',
    lblTasas: '//*[@text="TASAS"]',
    lblDetalle: '//*[@text="DETALLE"]',
    lblMotivoPrestamo: '//*[@text="MOTIVO DEL PRÉSTAMO"]',
    lblSistemaAmortizacion: '//*[@text="SISTEMA DE AMORTIZACIÓN"]',
    btnTyC: '~Términos y Condiciones',
    lblAnio: '//*[@text="AÑO 2021"]',
    lblAnio2: '//*[@text="AÑO 2022"]',
    btnCuota: '~Cuota 1',
    lblCapital: '//*[@text="Capital"]',
    lblIntereses: '//*[@text="Intereses"]',
    lblImpuestos: '//*[@text="Impuestos"]',
    lblArma: '//*[@text="Armá tu préstamo"]',
    lblCuantoDinero: '//*[@text="¿Cuánto dinero necesitás?"]',
    lblMontoPrestamo: '//*[@text="$ 494.000,00"]',
    lblComoDevolves: '//*[@text="¿Cómo lo devolvés?"]',
    btn36Cuotas: '~En 36 cuotas de 13722 pesos con 00 centavos por mes. Primera cuota es de 15094 pesos con 00 centavos.',
    inputMontoPrestamo: '//android.widget.ScrollView[@content-desc="Solicitarás 494000 pesos con 00 centavos. Podés pedir entre 20000 y 494000"]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.TextView',
    lblMontoMinMax: '//android.widget.ScrollView[@content-desc="Solicitarás 494000 pesos con 00 centavos. Podés pedir entre 20000 y 494000"]/android.view.ViewGroup/android.widget.TextView[2]',
    btnAceptarPrestamo: '~Aceptar',
    btn6Cuotas: '~En 6 cuotas de 20931 pesos con 00 centavos por mes. Primera cuota es de 23024 pesos con 00 centavos.',
    btn12Cuotas: '~En 12 cuotas de 10465 pesos con 00 centavos por mes. Primera cuota es de 11512 pesos con 00 centavos.',
    btn18Cuotas: '~En 18 cuotas de 6977 pesos con 00 centavos por mes. Primera cuota es de 7674 pesos con 00 centavos.',
    btn24Cuotas: '~En 24 cuotas de 5232 pesos con 00 centavos por mes. Primera cuota es de 5756 pesos con 00 centavos.',
    btn366Cuotas: '~En 36 cuotas de 3488 pesos con 00 centavos por mes. Primera cuota es de 3837 pesos con 00 centavos.',
    lblPrimeraCuota: '//*[@text="FECHA DE PRIMERA CUOTA"]',
    lblInputMonto: '//android.view.ViewGroup[@content-desc="Solicitarás 494000 pesos con 00 centavos. Podés pedir entre 20000 y 494000"]/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.TextView',
    lblCruz: '//android.widget.ScrollView[@content-desc="Solicitarás 494000 pesos con 00 centavos. Podés pedir entre 20000 y 494000"]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView',
    btnFlotanteSolicitarPrestamo: '~Solicitar préstamo',
    btnComenzar: '~Comenzar',
    btnMotivosArreglos: '~Arreglos del hogar / oficina',
    bannerOferta: '//*[@text="Tenés un préstamo preaprobado"]',
    bannerPedi: '//*[@text="y te lo acreditamos en el momento"]',
    btnAyuda: '~AYUDA',
    btnVerTodas: '~Ver todas',
    btnComoSolicitar: '//*[@text="¿Cómo solicitar un préstamo?"]',
    btnCuando: '//*[@text="¿Cuándo se acredita mi préstamo?"]',
    btnPuedoSolicitar: '//*[@text="¿Puedo solicitar otro monto o plazo?"]',
    btnNecesito: '//*[@text="¿Qué necesito para solicitar un préstamo?"]',
    btnPuedoCancelar: '//*[@text="¿Puedo cancelar mi préstamo de manera anticipada?"]',
    btnPuedoTener: '//*[@text="¿Puedo tener dos o más préstamos en simultáneo?"]',
    btnQueEs: '//*[@text="¿Qué es un préstamo preaprobado?"]',
    btnQueNecesito: '//*[@text="¿Qué necesito para solicitar un préstamo?"]',
    btnAQueSistema: '//*[@text="¿A qué sistema de amortización está sujeto mi préstamo?"]',
    btnQueSon: '//*[@text="¿Qué son CFT, TEA y TNA?"]',
    btnPrestamosFaqs: '~Desplegar PRÉSTAMOS',
    lblConfirmarPrestamo: '//*[@text="Confirmar préstamo"]',
    lblMontoAcreditar: '//*[@text="MONTO A ACREDITAR"]',
    lblMontoDevolver: '//*[@text="MONTO A DEVOLVER"]',
    lblFormasPago: '//*[@text="FORMAS DE PAGO"]',
    lblMontoPrimera: '//*[@text="MONTO DE LA PRIMERA CUOTA"]',
    btnAceptarTerminos: '~Aceptar términos y condiciones',
    btnSolicitar: '~Solicitar préstamo',
  },
  // ------------FIN Sección PRESTAMOS-------------


  HelpSection:{
  chatWithUs: '~Chateá con nosotros',
  //contactViewChatWithUs: '~accessibilityLabel.chatWithUs',
  help: '~AYUDA',
  helpIconUnlogged: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView', 
  helpIconlogged: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView',
  btnChatTopBarUnlinked: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView',
  btnChatTopBarLinked: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView',
  chatButton: '~CHAT',
  btnChatWhitUs: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.view.ViewGroup/androidx.appcompat.widget.LinearLayoutCompat/android.widget.TextView',
  contactUs_Android: '~Contactanos',
  contactUs_iOS: "(//*[@type='XCUIElementTypeOther' and @name='Contactanos'])[last()]",
  whatsappContact: '~Contactanos por Whatsapp',
  leaveYourSuggestions: '~Dejanos tu sugerencia',
  branchOffices: '~Sucursales',
  phones: '~Teléfono',
  email: '~Email',
  seeAll_iOS: '~Ver todas',
  seeAll_Android: '~Ver todas',
  dontReceiveRegistrationEmail: '~Ir a tema sugerido1',
  tipsForTakeSelphiePhoto: '~Ir a tema sugerido2',
  howTakeDniPhoto: '~Ir a tema sugerido3',
  openQuestion: '~Abrir pregunta',
  helpMoreOptions: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[6]/android.widget.ImageView',
  carrBeginRegister: '~Comenzá tu registro',
  carrLinkCellPhone: '~Vinculá tu celular',
  carrTakeFaceScreenShot: '~Tomá una foto de tu cara',
  carrTakeDniScreenShot: '~Tomá una foto de tu DNI',
  carrSwornDeclaration: '~Declaración jurada',
  carrTyC: '~Términos y Condiciones',
  carrCreatePassword: '~Creá tu clave',
  btnBack_Android: '~Navigate Up',
  btnBack_iOS: '~Ayuda en registro',
  ratePositive: '~Si',
  rateNegative: '~No',
  leaveSuggestion: '~accessibilityLabel.leaveSuggestion',
  btnConsumerDefense_Android: '~Defensa de las y los consumidores',
  btnConsumerDefense_iOS: '//*[contains(@name, "Defensa de las y los consumidores") and not(contains(@name , "Contactanos"))]',
  textFrecuentlyAsq_Android: "//*[@text='PREGUNTAS FRECUENTES']",
  textFrecuentlyAsq_iOS: "//*[@label='PREGUNTAS FRECUENTES']",

  },

    Suggestions:{
    textField: '~Compartinos tu idea',
    textImInterestedBeingContactedToTellMyExperience: "~Me interesa ser contactado para contar mi experiencia",
    textYourIdeasHelpsUs_Android: "//*[@text='¡Tus ideas nos ayudan a mejorar! Por consultas contactanos por Whatsapp al +54 11 5984-2523']", 
    textYourIdeasHelpsUs_iOS: "//*[@type = 'XCUIElementTypeStaticText' and @value='¡Tus ideas nos ayudan a mejorar! Por consultas contactanos por Whatsapp al +54 11 5984-2523']",                                                                        
    btnSend: '~accessibilityLabel.continueButton', 
    //btnSend: '~Enviar', 
    contactCheckbox: '~accessibilityLabel.checkBoxContainer',
    //msgSuccess: '~¡Muchas gracias',
    textSuggestionGrettings_Android: "//*[@text='Recibimos tu sugerencia.']",
    textSuggestionGrettings_iOS: '//*[@type = "XCUIElementTypeStaticText" and @value="Recibimos tu sugerencia."]',
    //msgSuccess_Android: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.TextView[1]',
    msgSuccess_Android: "//*[@text='Recibimos tu sugerencia.']",
    msgSuccess_iOS: '//*[@type = "XCUIElementTypeStaticText" and @value="Recibimos tu sugerencia."]',
    msgSuccessDetail:'/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.TextView[2]',
    btnFinish: '~Finalizar',
    btnNavigateUp:'~Navigate Up',
    },
    Chat:{
    msgResponseTime: '~¡Hola! Contanos en qué te podemos ayudar.',
    finishSession: '~Finalizar sesión',
    extendSession: '~Extender tiempo',
    textField_Android: '//*[@class="android.widget.EditText"]',
    textField_iOS: '//XCUIElementTypeTextView',
    //textField_iOS: '//XCUIElementTypeOther//XCUIElementTypeOther[2]//XCUIElementTypeTextView',
    textFieldAfterExtention_Android: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup[2]/android.widget.EditText',
    textFieldAfterExtention_iOS: '//*[@type = "XCUIElementTypeTextView"]',               
    btnSend: '~send',
    textUnlinked: '~Prueba_Chat',
    textFieldOutOfTime : './/*[contains(@name, "Fuera del horario")]/XCUIElementTypeOther[2]',
    msgLeaveMessage: '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView',
    technicalIssueSubmit: '~Entendido',
    welcomeChatText_Android: '//*[contains(@text, "Te contestaremos en el transcurso de algunas horas") or contains(@text, "DEJANOS TU MENSAJE Y TE RESPONDEREMOS EN EL TRANSCURSO DE ALGUNAS HORAS")]',
    welcomeChatText_iOS: '//*[contains(@name, "Te contestaremos en el transcurso de algunas horas")]',
    screenTitle_Android: '//*[@text="Chat"]',
    screenTitle_iOS: '//*[@name="Chat"]',
    welcomeTextHelpJuan_Android: '//*[@text="¡Hola Juan! Contanos en qué te podemos ayudar. Te contestaremos en el transcurso de algunas horas."]',
    welcomeTextHelpJuan_iOS: '//*[@name="¡Hola Juan! Contanos en qué te podemos ayudar. Te contestaremos en el transcurso de algunas horas."]',
    textNeedMoreTime: '//*[@text="¿Necesitás más tiempo?" or contains(@name, "¿Necesitás más tiempo?")]',
    textSecurityReasonsToExpireSession: '//*[@text="Por cuestiones de seguridad la sesión expirará pronto" or contains(@name, "Por cuestiones de seguridad la sesión expirará pronto")]',
    btnRetry_Android: '//*[@text="Reintentar"]',
    btnRetry_iOS: '//*[@name="Reintentar"]',
  },
    HelpLinkDevices:{
    note: '~Nota: Te recomendamos que elijas un email personal, porque los emails corporativos  pueden tener servicios que bloquean o filtran nuestro correo.',
    },

    OnboardingSeveralAttemptsWarning:{
      confirmButton: '~Contactanos',
      ignoreButton: '~Reintentar',
    },

    errors: {
      unabled_proccess_transaction_title: '~No pudimos procesar tu transacción',
      unabled_proccess_transaction_text:
        '~Hubo un error en el sistema. Te pedimos que lo vuelvas a intentar en otro momento.',
      unhandled_exception_title: '~No pudimos confirmar los datos ingresados',
      unhandled_exception_text: '~Hubo un error en el sistema. Te pedimos que lo vuelvas a intentar.',
      active_card_required:'~Activar una tarjeta',
      active_card_required_title: '~Se necesita una tarjeta activa para poder transferir',
      active_card_required_text: '~Solicitá una tarjeta de débito o activá una tarjeta virtual para poder transferir.',
      account_is_not_enabled_title: '~Tu cuenta no está habilitada para transferir',
      account_is_not_enabled_text: '~Comunicate con nosotros para recibir asistencia.',
      invalid_account_validation_title: '~Hay un problema con la validación de tu cuenta',
      invalid_account_validation_text: '~Comunicate con nosotros para recibir asistencia y poder transferir.',
      account_not_found_or_different_currency_title:
        '~No encontramos la cuenta o tiene una moneda distinta a la de origen.',
      contactUs:'~Contactanos'
    },
    rateAppModal:{
      btnBad: "~Mala",
      btnGood:"~Normal",
      btnExcellent:"~Muy buena",
      btnIgnore:"~En otro momento" ,
      btnCancelReview: '~accessibilityLabel.cancelButton',
      sendReview:'~accessibilityLabel.confirmButton' ,
      btnCancelSuggestion: '~accessibilityLabel.cancelButton',
      leaveSuggestion:'~accessibilityLabel.confirmButton' 
      },
      ToolTip: {
      dismissButton: '~Omitir',
      AccionesButton: '~Más acciones',
      btnUnderstood_Android: "//*[@text='Entendido']",
      btnUnderstood_iOS: '//*[contains(@label, "Entendido")]',
      btnUnderstood2_Android: "//*[@text='entendido']",
      btnUnderstood2_iOS: '//*[contains(@label, "entendido")]',
      },
      InsuranceFistEntry: {
        txtTitle: '//*[@text="Seguro Hogar"]',
        btnContinue: "~Continuar",
        AccionesButton: '~Más acciones',
      },
      InsuranceATMFistEntry: {
        txtPageTitle: '//*[@text="Seguro Retiro de efectivo"]',
        txtTitle: '//*[@text="Retirá efectivo con tranquilidad"]',
        txtSubtitle: '//*[@text="¡Conocé nuestra cobertura y los adicionales que tenemos para vos!"]',
        txtCoverageTitle: '//*[@text="COBERTURA"]',
        txtFirstCoverage: "~ROBO EN BOCAS DE EXTRACCIÓN",
        txtSecondCoverage: "~ROBO DE EFECTOS PERSONALES",
        txtThirdCoverage: "~ACCIDENTES PERSONALES",
        txtAssistanceTitle: '//*[@text="COBERTURA"]',
        txtFirstAssistance: "~ROBO EN BOCAS DE EXTRACCIÓN",
        txtSecondAssistance: "~ROBO DE EFECTOS PERSONALES",
        txtThirdAssistance: "~ACCIDENTES PERSONALES",
        btnContinue: "~Continuar",
        btnBack: "~VOLVER",
        btnHelp: "~AYUDA",
      },
      InsuranceSelectAddress: {
        btnContinue: "~Continuar",
        btnAddPostalCode: "~Ingresar nuevo código postal",
        txtTitle: '//*[@text="¿Sobre cuál dirección querés cotizar?"]',
        firstAddress_Android: "//*[*[contains(@text, '¿Sobre')]]/*[2]",
        firstAddress_iOS: "//*[*[*[@type='XCUIElementTypeStaticText' and contains(@name, 'Agente Institorio')]]]/*[1]/*[1]",
      },
      InsuranceAddAddress: {
        txtTitleATM: '//*[@text="Ingresá el código postal donde vivís"]',
        txtTitle: '//*[@text="Ingresá el código postal donde vivís"]',
        txtErrorZipcodeInvalid: '//*[@text="El código postal no existe"]',
        btnContinue: "~Continuar",
        boxAddress: '~Código Postal',
      },
      ConsumerDefense: {
        linkConsumerDefense: "~Para reclamos ingrese aquí",
        title_Android: '//*[@text="Defensa consumidores"]',
        title_iOS: '//*[@name="Defensa consumidores"]',
      },   
      InsuranceViewOffers: {
        txtTitle: '//*[@text = "Tu casa, a un paso de estar asegurada"]',
        txtATMTitle: '//*[@text = "Cotización"]',
        firstPlan_Android: '//*[*[@text="x mes"]][1]/*[1]',
        firstPlan_iOS: '//*[*[*[@type = "XCUIElementTypeStaticText" and contains(@name, "Tu")]]]/*[2]/*/*/*[1]',
        secondPlan_Android: '//*[*[@text="x mes"]][2]/*[1]',
        secondPlan_iOS: '//*[*[*[@type = "XCUIElementTypeStaticText" and contains(@name, "Tu")]]]/*[2]/*/*/*[3]',
        thirdPlan_Android: '//*[*[@text="x mes"]][3]/*[1]',
        thirdPlan_iOS: '//*[*[*[@type = "XCUIElementTypeStaticText" and contains(@name, "Tu")]]]/*[2]/*/*/*[5]',
        bntFirstPlanSeeCoverage_Android: '//*[@text = "Ver toda la cobertura"]',
        bntFirstPlanSeeCoverage_iOS: '//*[@name="Ver toda la cobertura del plan 1500"]',
        bntSecondPlanSeeCoverage_Android: '//*[@text = "Ver toda la cobertura"]',
        bntSecondPlanSeeCoverage_iOS: '//*[@name="Ver toda la cobertura del plan 1800"]',
        bntThirdPlanSeeCoverage_Android: '//*[@text = "Ver toda la cobertura"]',
        bntThirdPlanSeeCoverage_iOS: '//*[@name="Ver toda la cobertura del plan 2100"]',
        bntFirstPlanBuyInsurance_Android: '//*[@text = "Elegir plan"]',
        bntFirstPlanBuyInsurance_iOS: '//*[@name="Adquirir seguro 1500"]/*/*',
        bntSecondPlanBuyInsurance_Android: '//*[@text = "Elegir plan"]',
        bntSecondPlanBuyInsurance_iOS: '//*[@name="Adquirir seguro 1800"]/*/*',
        bntThirdPlanBuyInsurance_Android: '//*[@text = "Elegir plan"]',
        bntThirdPlanBuyInsurance_iOS: '//*[@name="Adquirir seguro 2100"]/*/*',
        bntBackToSelectAddress_Android: "~Navigate Up",
        bntBackToSelectAddress_iOS: "~Dirección de cotización",
        bntBackToAddAddress_Android: "~Navigate Up",
        bntBackToAddAddress_iOS: "~Nueva dirección",
        bntRetryLoadPage_Android: "~Reintentar",
        bntRetryLoadPage_iOS: '//*[@name="Reintentar"]/*/*'      
      },
      InsuranceATMViewOffers: {
        txtTitle: '//*[@text = "Tu efectivo, a un paso de estar asegurado"]',
        txtPlanValueTitle: '//*[*[@text = "PAGO MENSUAL"]]/*[1]',
        txtCoverageValue: '//*[*[@text = "Robo en bocas de extracción"]]/*[1]',
        txtPlanValue: '//*[*[@text = "PLAN"]]/*[4]',
        btnViewCoverage: '//*[@text = "Ver toda la cobertura"]'
      },
      InsuranceBPViewOffers: {
        txtTitle: '//*[@text = "Tu bolso, a un paso de estar asegurado"]',
        txtPlanValueTitle: '//*[*[@text = "PAGO MENSUAL"]]/*[1]',
        txtCoverageValue: '//*[*[@text = "Robo en bocas de extracción"]]/*[1]',
        txtPlanValue: '//*[*[@text = "PLAN"]]/*[4]',
        btnViewCoverage: '//*[@text = "Ver toda la cobertura"]'
      },
      InsuranceATMPlanDetails: {
        txtTitle: '//*[@text = "Plan 10000"]',
        txtCoverageValue: '//*[*[@text="PAGO MENSUAL"]]/*[@class="android.widget.TextView"][1]',
        txtCoverage1: "~Robo en bocas de extracción",
        txtCoverage2: "~Robo de efectos personales",
        txtCoverage3: "~Accidentes personales",
        txtCoverage4: "~Gastos de taxi / remis",
        txtCoverageValue1: '//*[*[@text="ROBO EN BOCAS DE EXTRACCIÓN"]]/*[@index=2]',
        txtCoverageValue2: '//*[*[@text="ROBO DE EFECTOS PERSONALES"]]/*[@index=2]',
        txtCoverageValue3: '//*[*[@text="ACCIDENTES PERSONALES"]]/*[@index=2]',
        txtCoverageValue4: '//*[*[@text="GASTOS DE TAXI / REMIS"]]/*[@index=2]',
        txtCoverageText1: '//*[contains(@text, "Te cubre robo de efectivo al momento de producida la extracción")]',
        txtCoverageText2: '//*[contains(@text, "Te cubre el gasto por el reemplazo de los siguientes documentos:")]',
        txtCoverageText3: '//*[contains(@text, "Te cubre la muerte violenta del Asegurado")]',
        txtCoverageText4: '//*[contains(@text, "Te cubre el traslado hasta el domicilio en caso de robo")]'

      },
      
      InsuranceBolsoPlanDetails: {
        txtTitle: '//*[@text = "Plan 10000"]',
        bntBack: "~Navigate Up",
        txtCoverageValue: '//*[*[@text="PAGO MENSUAL"]]/*[@class="android.widget.TextView"][1]',
        txtCoverage1: "~Suma Asegurada Total",
        txtCoverageValue1: '//*[*[@text="SUMA ASEGURADA TOTAL"]]/*[@index=2]',
        txtCoverageText1: '//*[contains(@text, "Tu seguro está compuesto por coberturas que forman la suma asegurada total.")]',
        txtSubCoverageBlock: "~Te acompañamos ante un siniestro con las siguientes sub coberturas:",
        txtSubCoverageTitle1: '//*[@text = "Robo de bolso / cartera"]',
        txtSubCoverageDescription1: '//*[contains(@text, "Te cubre el robo del bolso, maletín, cartera, mochila o riñonera")]',
        txtSubCoverageValue1: "~Monto a cubrir de Robo de bolso / cartera",
        txtSubCoverageTitle2: '//*[@text = "Robo del contenido"]',
        txtSubCoverageDescription2: '//*[contains(@text, "Te cubre el gasto por el robo del contenido de tu bolso, incluyendo")]',
        txtSubCoverageValue2: "~Monto a cubrir de Robo del contenido",
        txtSubCoverageTitle3: '//*[@text = "Gastos para reposición de documentos"]',
        txtSubCoverageDescription3: '//*[contains(@text, "Te cubre el gasto por el reemplazo de los siguientes documentos:")]',
        txtSubCoverageValue3: "~Monto a cubrir de Gastos para reposición de documentos",
        txtSubCoverageTitle4: '//*[@text = "Gastos de taxi / remis"]',
        txtSubCoverageDescription4: '//*[contains(@text, "Te cubre el traslado hasta el domicilio en caso de robo.")]',
        txtSubCoverageValue4: "~Monto a cubrir de Gastos de taxi / remis",
      },
      


      InsuranceATMConfirmPolicy: {
        txtTitle: '//*[@text = "Confirmar seguro"]',
        txtPlanValue: '//*[*[@content-desc="Pago mensual"]]/*[1]',
        txtPlanValueLabel: "~Pago mensual",
        txtPlanDetailsLabel: '//*[@text = "DETALLE DEL SEGURO"]',
        txtCoverageAmountLabel: "~Suma Asegurada",
        txtCoverageAmountValue: '//*[*[@content-desc="Suma Asegurada"]]/*[2]',
        txtCoverageTitle: "~Cobertura",
        txtCoverageDescription: "~Retiro de dinero siendo titular de tus tarjetas de débito o crédito por diferentes bocas de extracción: ATM, ventanilla en banco, Extra Cash, Rapipago, Pago Fácil y Cobro Express.",
        linkViewCoverage: "~Ver detalle de la cobertura",
        txtPaymentDetailsLabel: '//*[@text = "DETALLE DE PAGO"]',
        txtPaymentModeTitle: "~Modalidad",
        txtPaymentMode: "~Débito automático mensual",
        txtWayToPayTitle: "~Forma de pago",
        txtWayToPay: "~Las cuotas se debitan de tu caja de ahorro Nº 1000000149 de Banco del Sol",
        txtEmailTitle: "~Correo electrónico",
        txtEmailValue: '//*[*[@content-desc="Correo electrónico"]]/*[2]',
        linkPolicyConditions: "~accessibilityLabel.termsButton",
        checkboxPolicyConditions: "~Condiciones de la Póliza",
        btnContinue: "~Adquirir Seguro",
        

      },
      
      InsuranceATMTermAndConditions: {

        txtTitle: '//*[@text = "Condiciones de la Póliza"]',
        btnShare: "~COMPARTIR",
        txtShareMenu: '//*[contains(@text, "terms-atm-insurance")]',
        btnBack: "~Navigate Up"

      },
      InsuranceViewOffersErrorPage: {
        txtTitle: '//*[@text = "La cotización del seguro no está disponible"]',
        txtText: '//*[@text = "Volvé a intentar más tarde."]',
        bntRetry: '~Reintentar',
      },
      InsurancePlanDetails: {
        bntBack_Android: "~Navigate Up",
        bntBack_iOS: "~Dirección de cotización",
        bntSinisterServiceSection: '//*[@text = "TE ACOMPAÑAMOS ANTE UN SINIESTRO CON LOS SIGUIENTES SERVICIOS"]',
        txtPlan1500Title: '//*[@text="Plan 1500"]',
        bntFirstCoverageWithDescription: '~Monto a cubrir de Incendio Edificio',
        txtFirstCoverageWithDescription: '//*[*[@content-desc="Monto a cubrir de Incendio Edificio"]]/*[4]',
        bntFirstCoverageWithoutDescription: '~Monto a cubrir de Huracán, Ciclón, Tornado - Edificio',
        txtFirstCoverageWithoutDescription: '//*[*[@content-desc="Monto a cubrir de Huracán, Ciclón, Tornado - Edificio"]]/*[4]'
      },
  FaqScreen:{
    accountCollapse_Android: "//*[@text='CUENTA']",
    accountCollapse_iOS: '~Contraer CUENTA',
    accountExpand_Android: "//*[@text='CUENTA']",
    accountExpand_iOS: '~Desplegar CUENTA',
    cardCollapse_Android: "//*[@text='TARJETAS']",
    cardCollapse_iOS: '~Contraer TARJETAS',
    cardExpand_Android: "//*[@text='TARJETAS']",
    cardExpand_iOS: '~Desplegar TARJETAS',
    transferExpand_Android: "//*[@text='TRANSFERENCIAS']",
    transferExpand_iOS: '~Desplegar TRANSFERENCIAS', 
    transferCollapse_Android: "//*[@text='TRANSFERENCIAS']",
    transferCollapse_iOS: '~Contraer TRANSFERENCIAS', 
    howDoATransfer_Android: "//*[@text='¿Cómo hago una transferencia?']",
    howDoATransfer_iOS: '~¿Cómo hago una transferencia?', 
    helpfullInformation_Android: "//*[@text='¿Te sirvió esta información?']",
    helpfullInformation_iOS: '//*[contains(@name, "¿Te sirvió esta información?") and @visible="true"]',
  },
  HelpFaqExpand:{
    accounts: '~CUENTA',
    expandedFaq: '~accesibilityLabel.expandedFaqs',
    transfers: '~TRANSFERENCIAS',
    ratePositive: '~Si',
    rateNegative: '~No',
    leaveSuggestion: '~Dejar sugerencia',
    thanksForComment_Android: "//*[@text='¡Gracias! Dejanos tu sugerencia para seguir mejorando']",
    thanksForComment_iOS: '//*[contains(@name, "¡Gracias! Dejanos tu sugerencia para seguir mejorando")]',
    },
    obCameraInfo:{
      weCouldntRecognizeYou: "//*[@text='No pudimos reconocerte']",
      weDetectMoreThanOneFace: "//*[@text='Detectamos más de un rostro']",
      thePhotoMustBeFrontal: "//*[@text='La foto debe ser frontal']",
    },
  obDniInfo:{
      scanDocument: "//*[@text='Escanear documento']",
      filmYourFaceAgain: "//*[@text='Volvé a filmar tu cara']",
      invalidDni: "//*[@text='Tu DNI es inválido']",
      renaperPoorLigthConditions: "//*[@text='Escanear documento']",
     },
  onboardingHelpScreens:{
        textIfDidNotReceiveMail_Android: "//*[@text='Si no recibiste el email:']",
        textIfDidNotReceiveMail_iOS: "~Si no recibiste el email:",
        textRememberToHaveAHand_Android: "//*[@text='Recordá tener a mano:']",
        textRememberToHaveAHand_iOS: '~Recordá tener a mano:',
        textLastDniVersion_Android: "//*[@text='La última versión de tu DNI argentino.']",
        textLastDniVersion_iOS: '~La última versión de tu DNI argentino.',
        textCellWithAvailableCamera_Android: "//*[@text='Tu celular con las cámaras habilitadas.']",
        textCellWithAvailableCamera_iOS: '~Tu celular con las cámaras habilitadas.',
        textEmailDirection_Android: "//*[@text='Una dirección de email a la que puedas acceder fácilmente desde tu celular.']",
        textEmailDirection_iOS: '~Una dirección de email a la que puedas acceder fácilmente desde tu celular.',
        textRegistrationSteps_Android: "//*[@text='Pasos para registrarte']",
        textRegistrationSteps_iOS: '~Pasos para registrarte',
        textBeginRegister_Android: "//*[@text='Comenzá tu registro']",
        textBeginRegister_iOS: '~Comenzá tu registro',
        textLinkCell: '~Vinculá tu celular',
        textTakeSelfie_Android: "//*[@text='Tomá una foto de tu cara']",
        textTakeSelfie_iOS: '~Tomá una foto de tu cara',
        textGetAnEmailTolinkCell_Android: "//*[@text='Recibí tu email para vincular tu celular']",
        textGetAnEmailTolinkCell_iOS: '~Recibí tu email para vincular tu celular',
        textEmailAddress_Android: "//*[@text='Ingresá una dirección de email a la que puedas acceder desde tu celular.']",
        textEmailAddress_iOS: '~Ingresá una dirección de email a la que puedas acceder desde tu celular.',
        textThenOpenEmail_Android: "//*[@text='Luego, abrí el email que te enviamos desde el celular y presioná el botón 'Ingresar'.']",
        textThenOpenEmail_iOS: "Luego, abrí el email que te enviamos desde el celular y presioná el botón 'Ingresar'.",
        textBackToAppAndPressButtonResend_Android: "//*[@text='Volvé a la app y presioná el botón “Reenviar correo” para reintentarlo.']",
        textBackToAppAndPressButtonResend_iOS: '~Volvé a la app y presioná el botón “Reenviar correo” para reintentarlo.',
        textRecomendation_Android: "//*[@text='Recomendaciones:']",
        textRecomendation_iOS: '~Recomendaciones:',
        textCheckEmailOnUnwantedMailBox_Android: "//*[@text='Chequeá si el correo ingresó en tu casilla de correo no deseado, promociones u otros.']",
        textCheckEmailOnUnwantedMailBox_iOS: '~Chequeá si el correo ingresó en tu casilla de correo no deseado, promociones u otros.',
        textVerifyEnteredEmail_Android: "//*[@text='Comprobá que la dirección de email sea correcta.']",
        textVerifyEnteredEmail_iOS: '~Comprobá que la dirección de email sea correcta.',
        textMakeSureToUseSameDevice_Android: "//*[@text='Asegurate de acceder desde el mismo dispositivo con el que te vinculaste.']",
        textMakeSureToUseSameDevice_iOS: '~Asegurate de acceder desde el mismo dispositivo con el que te vinculaste.',
        textTakeDniPhoto_Android: "//*[@text='Tomá una foto de tu DNI']",
        textTakeDniPhoto_iOS: "//*[@type='XCUIElementTypeStaticText' and @name='Tomá una foto de tu DNI']",
        crBtnTakeDniPhoto_Android: "//*[@text='Tomá una foto de tu DNI']",
        crBtnTakeDniPhoto_iOS: "(//*[@type='XCUIElementTypeOther' and @name='Tomá una foto de tu DNI'])[last()]",
        textToValidateYourIdentity_Android: "//*[@text='Para validar tu identidad necesitamos que aceptes los permisos de cámara de tu celular.']",
        textToValidateYourIdentity_iOS: '~Para validar tu identidad necesitamos que aceptes los permisos de cámara de tu celular.',
        textFocusYourFaceForward_Android: "//*[@text='Enfocá tu cara y mirá al frente hasta que el círculo naranja se complete']",
        textFocusYourFaceForward_iOS: '~Enfocá tu cara y mirá al frente hasta que el círculo naranja se complete',
        textPhotowillBeTakenAutomatically_Android: "//*[@text='La foto se tomará automáticamente.']",
        textPhotowillBeTakenAutomatically_iOS: '~La foto se tomará automáticamente.',
        textFilmInBrightPlace_Android: "//*[@text='Filmate en un lugar luminoso y en lo posible con fondo blanco.']",
        textFilmInBrightPlace_iOS: '~Filmate en un lugar luminoso y en lo posible con fondo blanco.',
        textDontUseGlasses_Android: "//*[@text='No uses anteojos y chequeá que el cabello no te tape la cara.']",
        textDontUseGlasses_iOS: '~No uses anteojos y chequeá que el cabello no te tape la cara.',
        textMakeSureDontHavePeopleAround_Android: "//*[@text='Asegurate de no tener personas alrededor.']",
        textMakeSureDontHavePeopleAround_iOS: '~Asegurate de no tener personas alrededor.',
        textSwornDeclaration_Android: "//*[@text='Declaración Jurada']",
        textSwornDeclaration_iOS: '~Declaración Jurada',
        textFrameDniFrontAndBackInRectangle_Android: "//*[@text='Encuadrá el frente y luego el dorso de tu DNI en el área que indica el rectángulo.']",
        textFrameDniFrontAndBackInRectangle_iOS: '~Encuadrá el frente y luego el dorso de tu DNI en el área que indica el rectángulo.',
        textDniPhotowillBeTakenAutomatically_Android: "//*[@text='La imagen se tomará automáticamente una vez que reconozca el documento.']",
        textDniPhotowillBeTakenAutomatically_iOS: '~La imagen se tomará automáticamente una vez que reconozca el documento.',
        textCheckIfSeeDataIntoRectangle_Android: "//*[@text='Antes de continuar, verificá que se vean todos los datos dentro del rectángulo.']",
        textCheckIfSeeDataIntoRectangle_iOS: '~Antes de continuar, verificá que se vean todos los datos dentro del rectángulo.',
        textUseLastDniVersion_Android: "//*[@text='Usá la última versión de tu DNI.']",
        textUseLastDniVersion_iOS: '~Usá la última versión de tu DNI.',
        textLeaveItOnCleanSurface_Android: "//*[@text='Apoyalo en una superficie lisa y opaca.']",
        textLeaveItOnCleanSurface_iOS: '~Apoyalo en una superficie lisa y opaca.',
        textTakeDniPhotoInBrightPlaece_Android: "//*[@text='Tomá la foto en un lugar con buena iluminación y no dejes que refleje luz directa en el plástico de tu DNI.']",
        textTakeDniPhotoInBrightPlaece_iOS: '~Tomá la foto en un lugar con buena iluminación y no dejes que refleje luz directa en el plástico de tu DNI.',
        textContactUsIfYourCameraIsNotAvailable_Android: "//*[@text='Si no tenés disponibles las cámaras de tu dispositivo, contactanos para recibir asistencia.']",
        textContactUsIfYourCameraIsNotAvailable_iOS: '~Si no tenés disponibles las cámaras de tu dispositivo, contactanos para recibir asistencia.',
        textDniIssuedIn2011_Android: "//*[@text='Nota: Si tu DNI fue emitido en el 2011 o tiene un plastificado con reflejo violeta es posible que no puedas continuar con el registro, contactate con nosotros por WhatsApp al +(54)11-5984-2523']",
        textDniIssuedIn2011_iOS: '~Nota: Si tu DNI fue emitido en el 2011 o tiene un plastificado con reflejo violeta es posible que no puedas continuar con el registro, contactate con nosotros por WhatsApp al +(54)11-5984-2523',
        textTermsAndConditions_Android: "//*[@text='Términos y Condiciones']",
        textTermsAndConditions_iOS: '~Términos y Condiciones',
        carrTermsAndConditions_Android: "//*[@text='Términos y Condiciones']",
        carrTermsAndConditions_iOS: "(//*[@type='XCUIElementTypeOther' and @name='Términos y Condiciones'])[last()]",
        textDeclarePepFacta_Android: "//*[@text='Declará si aplicás como Persona Expuesta Políticamente, Sujeto Obligado o FATCA/CRS.']",
        textDeclarePepFacta_iOS: '~Declará si aplicás como Persona Expuesta Políticamente, Sujeto Obligado o FATCA/CRS.',
        textWhoIsPEP_Android: "//*[@text='¿Quién es una Persona Expuesta Políticamente?']",
        textWhoIsPEP_iOS: '~¿Quién es una Persona Expuesta Políticamente?',
        textPEPIsAnswer_Android: "//*[@text='(PEP) Son los individuos que desempeñan o desempeñaron funciones públicas destacadas.']",
        textPEPIsAnswer_iOS: '~(PEP) Son los individuos que desempeñan o desempeñaron funciones públicas destacadas.',
        textWhoIsSObligatedSubject_Android: "//*[@text='¿Quién es un Sujeto Obligado?']",
        textWhoIsSObligatedSubject_iOS: '¿Quién es un Sujeto Obligado?',
        textObligatedSubjectIsAnswer_Android: "//*[@text='Cualquier persona física o jurídico colectiva y cualquier otra autoridad, estatal o municipal, que reciba recursos públicos.']",
        textObligatedSubjectIsAnswer_iOS: '~Cualquier persona física o jurídico colectiva y cualquier otra autoridad, estatal o municipal, que reciba recursos públicos.',
        textWhoIsFacta_Android: "//*[@text='¿Quién es un FATCA/CRS?']",
        textWhoIsFacta_iOS: '~¿Quién es un FATCA/CRS?',
        textFactaIsAnswer_Android: "//*[@text='Aquel que tiene residencia fiscal en el exterior.']",
        textFactaIsAnswer_iOS: '~Aquel que tiene residencia fiscal en el exterior.',
        textCreatePassword_Android: "//*[@text='Creá tu clave']",
        textCreatePassword_iOS: '~Creá tu clave',
        carrCreatePassword_Android: "//*[@text='Creá tu clave']",
        carrCreatePassword_iOS: "(//*[@type='XCUIElementTypeOther' and @name='Creá tu clave'])[last()]",
        textToCreatePassYouMustAcceptTyC_Android: "//*[@text='Para poder crear tu cuenta, vas a tener que aceptar los Términos y Condiciones y la Política de Privacidad.']",
        textToCreatePassYouMustAcceptTyC_iOS: '~Para poder crear tu cuenta, vas a tener que aceptar los Términos y Condiciones y la Política de Privacidad.',
        textWhatDoesTheDocsConsist_Android: "//*[@text='¿En qué consiste la documentación?']",
        textWhatDoesTheDocsConsist_iOS: '~¿En qué consiste la documentación?',
        textAcceptPersonalAndBiometricsDataConcent_Android: "//*[@text='Aceptás el consentimiento de los datos biométricos y personales para operar.']",
        textAcceptPersonalAndBiometricsDataConcent_iOS: '~Aceptás el consentimiento de los datos biométricos y personales para operar.',
        textAuthorizeToBDSToWhatsappOrPhoneContact_Android: "//*[@text='Autorizás a Banco del Sol a contactarte por teléfono, WhatsApp o mensaje de texto.']",
        textAuthorizeToBDSToWhatsappOrPhoneContact_iOS: '~Autorizás a Banco del Sol a contactarte por teléfono, WhatsApp o mensaje de texto.',
        textCanWithdrawMoneyAtAnyTimeWithoutCostTroughAvailableMeans_Android: "//*[@text='Podés retirar tu dinero en cualquier momento sin costo a través de los medios disponibles.']",
        textCanWithdrawMoneyAtAnyTimeWithoutCostTroughAvailableMeans_iOS: '~Podés retirar tu dinero en cualquier momento sin costo a través de los medios disponibles.',
        textWeWillNotChargeForTransferringAccountCheckOrCollectMoney_Android: "//*[@text='No te cobraremos comisión por transferir, revisar tu saldo, o cobrar dinero.']",
        textWeWillNotChargeForTransferringAccountCheckOrCollectMoney_iOS: '~No te cobraremos comisión por transferir, revisar tu saldo, o cobrar dinero.',
        textCreateNumericPassWith6digits_Android: "//*[@text='Creá una clave numérica de 6 dígitos que puedas acordarte facilmente y confirmala.']",
        textCreateNumericPassWith6digits_iOS: '~Creá una clave numérica de 6 dígitos que puedas acordarte facilmente y confirmala.',
        textForYourSecurityWeWillPromptToYouAtSignInToTheApp_Android: "//*[@text='Para cuidar tu seguridad, te la vamos a pedir al iniciar sesión en el banco.']",
        textForYourSecurityWeWillPromptToYouAtSignInToTheApp_iOS: '~Para cuidar tu seguridad, te la vamos a pedir al iniciar sesión en el banco.',
        textTipsForCreatingYourPassword_Android: "//*[@text='Consejos para crear tu clave:']",
        textTipsForCreatingYourPassword_iOS: '~Consejos para crear tu clave:',
        textDoNotEnter3EqualOrConsecutiveDigits_Android: "//*[@text='No ingreses 3 dígitos iguales ni consecutivos.']",
        textDoNotEnter3EqualOrConsecutiveDigits_iOS: '~No ingreses 3 dígitos iguales ni consecutivos.',
        textAvoidIncludePersonalData_Android: "//*[@text='Evitá incluir datos personales.']",
        textAvoidIncludePersonalData_iOS: '~Evitá incluir datos personales.',
        textReadyYouCouldAlreadyRegisterAtBancoDelSol_Android: "//*[@text='¡Listo, ya te pudiste registrar en Banco del Sol!']",
        textReadyYouCouldAlreadyRegisterAtBancoDelSol_iOS: '~¡Listo, ya te pudiste registrar en Banco del Sol!',
        textYouWillReceiveConfirmationEmailOnceYouFinishRegistration_Android: "//*[@text='Vas a recibir un mail de confirmación una vez que finalices el registro.']",
        textYouWillReceiveConfirmationEmailOnceYouFinishRegistration_iOS: '~Vas a recibir un mail de confirmación una vez que finalices el registro.',
        textIDidNotReceiveRegistrationEmail_Android: "//*[@text='No recibí el email de registro']",
        textIDidNotReceiveRegistrationEmail_iOS: "//*[@type='XCUIElementTypeOther' and @name='Ir a tema sugerido1']",
        textTipsToTakeYourSelfie_Android: "//*[@text='Consejos para sacar tu foto']",
        textTipsToTakeYourSelfie_iOS: "//*[@type='XCUIElementTypeOther' and @name='Ir a tema sugerido2']",
        textHowToTakeDniPhoto_Android: "//*[@text='Cómo tomar la foto de mi DNI']",
        textHowToTakeDniPhoto_iOS: "//*[@type='XCUIElementTypeOther' and @name='Ir a tema sugerido3']",
        textForRegistrationWeWillNeedYouToHaveYourCellPhoneCamerasAvailableAndHaveYourIDAtHand_Android: "//*[@text='Para el registro vamos a necesitar que tengas las cámaras de tu celular disponibles y tengas a mano tu DNI.']",
        textForRegistrationWeWillNeedYouToHaveYourCellPhoneCamerasAvailableAndHaveYourIDAtHand_iOS: '~Para el registro vamos a necesitar que tengas las cámaras de tu celular disponibles y tengas a mano tu DNI.',
        btnBack_Android: '~Navigate Up',
        btnBack_iOS: '~Ayuda en registro',
      },
  InsuranceDataAddress: {
      btnBack: '~Navigate Up',
      txtTitle_Android: '//*[@text="Formulario dirección"]',
      txtTitle_iOS: '//*[@value="Formulario dirección"]',    
      boxStreet: '~Calle',
      boxNumber: '~Altura',
      chkBoxHouse: '~accesibilityLabel.form.house',
      chkBoxApartment: '~accesibilityLabel.form.apartment',
      boxDpto: '~Piso/Dpto',
      boxReference: '~Referencia (opcional)',
      boxPostalCode: '~Código postal',
      boxCountry: '~Provincia',
      comboCity: '~Localidad',
      boxPhone: '~Teléfono de contacto',
      boxPhoneCode: '~Cód. área',
      btnContinue: "~Continuar",
      txtCompleteDataError_Android: '//*[@text="Completá todos los campos"]',
      txtCompleteDataError_iOS: '//*[@name="Completá todos los campos"]',
      btnAcept_Android: '//*[@text="Aceptar"]',
      btnAcept_iOS: '//*[@name="Aceptar"]',
      boxStreetIncompletedError: '//*[*[@text="Calle"]]/following::*[@text="Este dato es requerido"][1]',
      boxNumberIncompletedError: '//*[*[@text="Altura"]]/following::*[@text="Este dato es requerido"][1]',
      boxDptoIncompletedError: '//*[*[@text="Piso/Dpto"]]/following::*[@text="Este dato es requerido"][1]',
      boxCityIncompletedError: '//*[*[@text="Localidad"]]/following::*[@text="Este dato es requerido"][1]',
      boxPhoneIncompletedError: '//*[*[@text="Teléfono de contacto"]]/following::*[@text="Este dato es requerido"][1]',
      btnback: '',
      txtErrorMore8CharacterPhone: '//*[@text="Superaste el máximo de 8 caracteres"]',
      txtErrorLess6CharacterPhone: '//*[@text="El mínimo de caracteres es de 6"]',
      txtErrorMore4CharacterCodePhone: '//*[@text="Superaste el máximo de 4 caracteres"]',
      txtErrorLess2CharacterCodePhone: '//*[@text="El mínimo de caracteres es de 2"]',
      txtErrorLessInvalidNumberPhone: '//*[@text="Número incorrecto"]'
      

    },
    InsuranceConfirmPolicy: {
      bntBack_Android: "~Navigate Up",
      bntBack_iOS: "~Formulario de dirección",
      txtTitle_Android: '//*[@text="Confirmar seguro"]',
      txtTitle_iOS: '//*[@value="Confirmar seguro"]',
      txtPolicyTitleValue: '//*[*[contains(@text,"PAGO MENSUAL")]]/*[1]',
      txtPolicyTitlePlan: '//*[contains(@text,"PLAN")]',
      txtPolicyPlan: '//*[contains(@text,"PLAN")]',
      txtPolicyValue: '//*[*[contains(@text,"PLAN")]]/*[2]',
      txtAddress: '//*[*[contains(@text,"DIRECCIÓN")]]/*[2]',
      txtEMail: '//*[*[contains(@text,"CORREO ELECTRÓNICO")]]/*[2]',
      txtSSNText: '//*[*[contains(@text,"EMPRESA ASEGURADORA")]]/*[3]',
      txtSSNPhone: '//*[*[contains(@text,"EMPRESA ASEGURADORA")]]/*[4]',
      txtSSNURL: '//*[*[contains(@text,"EMPRESA ASEGURADORA")]]/*[5]',
      txtModality: '//*[*[contains(@text,"MODALIDAD")]]/*[2]',
      txtMethodPayment: '//*[*[contains(@text,"FORMA DE PAGO")]]/*[2]',
      txtAmountQuote: '//*[*[contains(@text,"MONTO PRIMERA CUOTA")]]/*[2]',
      chkTermsAndConditions: '//*[*[contains(@text,"Leí y acepto las")]]/*[1]',
      btnContinue: "~Adquirir Seguro",
      bntPlanSeeCoverage: '//*[@text = "Ver detalle de la cobertura"]',
    },
    FixedTerm: {
      txtAmount: '//*[@text="$ 0"]',
      btnUnMes: '//*[@text="1 Mes"]',
      btnDosMeses: '//*[@text="2 Meses"]',
      btnTresMeses: '//*[@text="3 Meses"]',
      btnCrearPlazoFijo: "~Crear Plazo Fijo",
      btnVerVoucher: "~Ver comprobante",
      txtPlazoFijoRealizado: '//*[@text="Plazo Fijo realizado"]',
      btnFinalizarPlazo: "~Finalizar",
      btnVerInversiones: "~Ver mis inversiones",
    },
    InsuranceNewPolicySuccess: {
      txtTitle: '//*[@text = "Hogar Asegurado"]',
      bntFinish: "~Finalizar"
    },

    InsuranceNewATMPolicySuccess: {
      txtTitle: '//*[@text = "Retiro de efectivo Asegurado"]',
      txtSubTitle: '//*[contains(@text, "pmallo@bdsol.com.ar")]',
      btnFinish: "~Finalizar",
      btnBack: "~VOLVER"
    },
    InsuranceHome: {
      txtTitle: '//*[@text="Seguros"]',
      bntNewInsurance: '//*[@text="Solicitá un nuevo seguro"]',
      policyListEmpty: '//*[@text="Aún no tenés seguros contratados"]',
      policyElement: '//*[@class="android.widget.ScrollView"]/*/*',
      bntBack: "~Navigate Up",
      btnPolizasSeleccion: "~Seleccionar todos",
      txtSeleccion: '//*[@text="1 seleccionados"]',
      btnAdhesion: "~Quiero adherirlos",
      txtAdhesionOk: "~Tus seguros se adhirieron",
      btnAdhesionFinalizar: "~Finalizar",
      btnVolver: "~VOLVER",
      BPPolicy: "~Bolso",
    },
    InsurancePolicyDetails: {
      txtTitle: '//*[@text = "Detalle"]',
      bntCustomerServicePhone: '//*[@text="0800-444-2850"]',
      bntSinisterReport: "~Denunciar un siniestro",
      bntUnsubscribeInsurance: "~Dar de baja el seguro"
    },
    InsuranceSinisterReport: {
      txtTitle: '//*[@text = "Denuncia"]',
      txtFisrtText: "~Estamos para vos en los momentos más difíciles",
      bntCallSancor: "~Llamar a la línea Sancor",
    },
    InsuranceUnsubscribeInfo: {
      txtTitle: '//*[@text = "Baja del Seguro"]',
      txtFirstText: '~Si te dás de baja tu hogar quedará sin cobertura',
      txtATMFirstText: '//*[@text = "Si te das de baja, tu retiro de efectivo quedará sin cobertura"]',
      txtBPFirstText: '//*[@text = "Si te dás de baja, tu bolso quedará sin cobertura"]',
      bntUnsubscribe: "~Darme de baja",
      bntBack: "~Navigate Up",
    },
    InsuranceReasonUnsubscribe: {
      bntBack: "~Navigate Up",
      txtTitle: '//*[@text = "Contanos el motivo de la baja"]',
      bntFirstReason: '~Ya no lo necesito',
      btnContinue: "~Continuar",
    },
    InsuranceUnsubscribeModal: {
      bntBack: "~Navigate Up",
      txtTitle: '//*[@text = "Vas a dar de baja tu seguro de hogar"]',
      txtATMTitle: '//*[@text = "Vas a dar de baja tu seguro de Retiro de efectivo"]',
      txtBPTitle: '//*[@text = "Vas a dar de baja tu seguro de bolso"]',
      txtText: '//*[@text = "Este paso es definitivo y la cobertura quedará sin efecto"]',
      bntCancelar: '~Cancelar',
      btnUnsubscribe: "~Darme de baja",
    },
    InsuranceUnsubscribeSuccessfully: {
      bntBack: "~VOLVER",
      txtTitle: '//*[@text = "Te diste de baja"]',
      txtText: '//*[@text = "A partir de ahora, tu seguro de hogar quedará sin efecto."]',
      bntFinish: '~Finalizar',
      
    },
    InsuranceATMUnsubscribeSuccessfully: {
      bntBack: "~VOLVER",
      txtTitle: '//*[@text = "Diste de baja tu seguro"]',
      txtText: '//*[@text = "A partir de ahora, tu seguro de retiro de efectivo quedará sin efecto."]',
      bntFinish: '~Finalizar',
      
    },

    InsuranceBPUnsubscribeSuccessfully: {
      bntBack: "~VOLVER",
      txtTitle: '//*[@text = "Diste de baja tu seguro"]',
      txtText: '//*[@text = "A partir de ahora, tu seguro de bolso quedará sin efecto."]',
      bntFinish: '~Finalizar',
      
    },
    InsuranceUnsubscribeError: {
      bntBack: "~Navigate Up",
      txtTitle: '//*[@text = "No pudimos procesar tu solicitud en este momento"]',
      bntRetry: "~Reintentar"
    },
    InsuranceNewPolicyType: {
      btnBack: "~Navigate Up",
      btnHelp: "~AYUDA",
      txtTitle: '//*[@text = "Seguros"]',
      txtSubtitle: '//*[@text = "¡Conocé la oferta de seguros que tenemos para vos!"]',
      btnNewPolicyHome: "~Hogar",
      btnNewPolicyAtm: "~Retiro de efectivo",
      btnNewPolicyBP: "~Bolso",
      btnComingSoon: "~¡Próximamente!"
    },

    InsuranceBPFistEntry: {
      txtPageTitle: '//*[@text="Seguro Bolso"]',
      txtTitle: '//*[@text="Protegé tu bolso y el contenido que llevas en él"]',
      txtSubtitle: '//*[@text="¡Conocé nuestra cobertura y los adicionales que tenemos para vos!"]',
      txtCoverageTitle: '//*[@text="COBERTURA"]',
      txtFirstCoverage: "~ROBO DE BOLSO / CARTERA",
      txtSecondCoverage: "~ROBO DEL CONTENIDO",
      txtThirdCoverage: "~GASTOS PARA REPOSICIÓN DE DOCUMENTOS",
      txtFourthCoverage: "~GASTOS DE TAXI / REMIS",
      btnContinue: "~Continuar",
      btnBack: "~VOLVER",
      btnHelp: "~AYUDA",
    },


    
pushNotification:{
  MesaDeTrabajoDeTi: '//*[@text="Mesa de Trabajo TI"]',
},
CneFailure: {
  title: "//*[@text='Estamos validando tus datos']",
  understood: "//*[@text='Entendido']",
},
OccupationScreen:{
  btnOccupation: "//*[@text='Ocupación']",
},
OccupationDropDownList:{
  optStudent: "//*[@text='Estudiante']",
  btnConfirm: "//*[@text='Confirmar']",
},

    CardsTracking: {
      txtTrackingStatus1: '//*[contains(@text, "Estamos preparando tu tarjeta")]',
      txtTrackingStatus1Desc: '//*[contains(@text, "Pronto te la enviaremos")]',
      txtTrackingStatus2: '//*[contains(@text, "Tu tarjeta está en camino")]',
      txtTrackingStatus2Desc: '//*[contains(@text, "Te avisamos cuando estamos por llegar")]',
      txtTrackingStatus3: '//*[contains(@text, "No te encontramos")]',
      txtTrackingStatus3Desc: '//*[contains(@text, "No te preocupes, volvemos a pasar")]',
      txtTrackingStatus4: '//*[contains(@text, "Tarjeta entregada")]',
      txtTrackingStatus4Desc: '//*[contains(@text, "¡Ya podes activarla!")]',
      txtTrackingStatus5: '//*[contains(@text, "No pudimos entregar tu tarjeta")]',
      txtTrackingStatus5Desc: '//*[contains(@text, "Te visitamos y no encontramos a nadie")]',
      txtTrackingStatus6: '//*[contains(@text, "Tarjeta en Sucursal OCA")]',
      txtTrackingStatus6Desc: '//*[contains(@text, "Ya podes retirar tu tarjeta por la sucursal")]',
      txtActiveCardTitle: "//*[@text='Activar tarjeta']",
      txtTitle: "//*[@text='Seguimiento']",
      bntCardActive: '~Activar',
      bntContactUs: '~Contactanos',
      bntBack: "~VOLVER",
      bntHelp: "~AYUDA",
    },


}

export default listSelectors
