Feature: OnboardingHelp

  Como cliente
  Quiero poder visualizar pantallas de ayuda contextualizadas durante el onboarding
  
  @regression_green @regression
  Scenario: Pantalla de error email enviado vinculando cuenta rutea a pantalla de ayuda HELP_Home.
    When user tap on "Welcome.loginButton"
    When user tap on "LinkInfo.acceptButton"
    When user types "emailfjdakjfak@gmail.com" on field "EmailValidation.inputEmail"
    When user tap on "EmailValidation.continueButton"
    When user tap on "EmailVerificationSent.textNeedHelp"
    Then user see text on screen "HelpSection.textFrecuentlyAsq"

  @regression_green @regression
  Scenario: Pantalla de error email enviado durante onboarding rutea a pantalla de ayuda HELP_LINK_DEVICE
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "LinkInfo.acceptButton"
    When user types "cualquieremail@gmail.com" on field "EmailManualLogin.inputEmail"
    When user tap on "EmailManualLogin.continueButton"
    When user tap on "EmailVerificationSent.textNeedHelp"
    And user scrolls to see element "onboardingHelpScreens.textIfDidNotReceiveMail"

     @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
  Scenario: Cliente ingresar a opcion del carrousel Comenzá tu registro desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrBeginRegister"
    Then user scrolls to see element "onboardingHelpScreens.textRememberToHaveAHand"
    Then user scrolls to see element "onboardingHelpScreens.textLastDniVersion"
    Then user scrolls to see element "onboardingHelpScreens.textCellWithAvailableCamera"
    Then user scrolls to see element "onboardingHelpScreens.textEmailDirection"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.textBeginRegister"
    Then user scrolls to see element "onboardingHelpScreens.textLinkCell"
    Then user scrolls to see element "onboardingHelpScreens.textTakeSelfie"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

    @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
Scenario: Cliente ingresar a opcion del carrousel Vinculá tu celular desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrLinkCellPhone"
    Then user scrolls to see element "onboardingHelpScreens.textGetAnEmailTolinkCell"
    Then user scrolls to see element "onboardingHelpScreens.textEmailAddress"
    And user scrolls to see element "onboardingHelpScreens.textIfDidNotReceiveMail" 
    Then user scrolls to see element "onboardingHelpScreens.textBackToAppAndPressButtonResend"  
    Then user scrolls to see element "onboardingHelpScreens.textRecomendation"
    Then user scrolls to see element "onboardingHelpScreens.textCheckEmailOnUnwantedMailBox"
    Then user scrolls to see element "onboardingHelpScreens.textVerifyEnteredEmail"
    Then user scrolls to see element "onboardingHelpScreens.textMakeSureToUseSameDevice"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.textLinkCell"
    Then user scrolls to see element "onboardingHelpScreens.textTakeSelfie"
    Then user scrolls to see element "onboardingHelpScreens.textTakeDniPhoto"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

    @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
  Scenario: Cliente ingresar a opcion del carrousel Tomá una foto de tu cara desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrTakeFaceScreenShot"
    Then user scrolls to see element "onboardingHelpScreens.textTakeSelfie"
    Then user scrolls to see element "onboardingHelpScreens.textToValidateYourIdentity"
    Then user scrolls to see element "onboardingHelpScreens.textFocusYourFaceForward"
    Then user scrolls to see element "onboardingHelpScreens.textPhotowillBeTakenAutomatically"
    Then user scrolls to see element "onboardingHelpScreens.textRecomendation"
    Then user scrolls to see element "onboardingHelpScreens.textFilmInBrightPlace"
    Then user scrolls to see element "onboardingHelpScreens.textDontUseGlasses"
    Then user scrolls to see element "onboardingHelpScreens.textMakeSureDontHavePeopleAround"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.textTakeSelfie"
    Then user scrolls to see element "onboardingHelpScreens.textTakeDniPhoto"
    Then user scrolls to see element "HelpSection.carrSwornDeclaration"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"
    
  @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
  Scenario: Cliente ingresar a opcion del carrousel Toma una foto de tu DNI desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrTakeDniScreenShot"
    And user see text on screen "onboardingHelpScreens.textTakeDniPhoto"
    Then user scrolls and click on button or text "onboardingHelpScreens.textFrameDniFrontAndBackInRectangle"
    Then user scrolls and click on button or text "onboardingHelpScreens.textDniPhotowillBeTakenAutomatically"
    Then user scrolls and click on button or text "onboardingHelpScreens.textCheckIfSeeDataIntoRectangle"
    Then user scrolls to see element "onboardingHelpScreens.textRecomendation"
    Then user scrolls to see element "onboardingHelpScreens.textUseLastDniVersion"
    Then user scrolls to see element "onboardingHelpScreens.textLeaveItOnCleanSurface"
    Then user scrolls to see element "onboardingHelpScreens.textTakeDniPhotoInBrightPlaece"
    Then user scrolls to see element "onboardingHelpScreens.textContactUsIfYourCameraIsNotAvailable"
    Then user scrolls to see element "onboardingHelpScreens.textDniIssuedIn2011"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.crBtnTakeDniPhoto"
    Then user scrolls to see element "HelpSection.carrSwornDeclaration"
    Then user scrolls to see element "onboardingHelpScreens.textTermsAndConditions"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

  @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression @skip() @ISSUE
  Scenario: Cliente ingresar a opcion del carrousel Declaración Jurada desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrSwornDeclaration"
    Then user see text on screen "onboardingHelpScreens.textSwornDeclaration"
    Then user scrolls to see element "onboardingHelpScreens.textDeclarePepFacta"
    Then user scrolls to see element "onboardingHelpScreens.textWhoIsPEP"
    Then user scrolls to see element "onboardingHelpScreens.textPEPIsAnswer"
    Then user scrolls to see element "onboardingHelpScreens.textWhoIsSObligatedSubject"
    Then user scrolls to see element "onboardingHelpScreens.textObligatedSubjectIsAnswer"
    Then user scrolls to see element "onboardingHelpScreens.textWhoIsFacta"
    Then user scrolls to see element "onboardingHelpScreens.textFactaIsAnswer"  
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "HelpSection.carrSwornDeclaration"
    Then user scrolls to see element "onboardingHelpScreens.textTermsAndConditions"
    Then user scrolls to see element "onboardingHelpScreens.textCreatePassword"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

  @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
  Scenario: Cliente ingresar a opcion del carrousel Términos y Condiciones desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrTyC"
    Then user scrolls to see element "onboardingHelpScreens.textTermsAndConditions"
    Then user scrolls to see element "onboardingHelpScreens.textToCreatePassYouMustAcceptTyC"
    Then user scrolls to see element "onboardingHelpScreens.textWhatDoesTheDocsConsist"
    Then user scrolls to see element "onboardingHelpScreens.textAcceptPersonalAndBiometricsDataConcent"
    Then user scrolls to see element "onboardingHelpScreens.textAuthorizeToBDSToWhatsappOrPhoneContact"
    Then user scrolls to see element "onboardingHelpScreens.textCanWithdrawMoneyAtAnyTimeWithoutCostTroughAvailableMeans"
    Then user scrolls to see element "onboardingHelpScreens.textWeWillNotChargeForTransferringAccountCheckOrCollectMoney"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.carrTermsAndConditions" 
    Then user scrolls to see element "onboardingHelpScreens.textCreatePassword"
    Then user scrolls to see element "onboardingHelpScreens.textBeginRegister"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

  @bdsd-8986 @bdsd-9025 @BDSD-10745 @regression_green @regression
  Scenario: Cliente ingresar a opcion del carrousel Creá tu clave desde helpSection del onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    When user tap on "TopBar.helpButton"
    When user scrolls to left and tap on button "HelpSection.carrCreatePassword"
    Then user scrolls to see element "onboardingHelpScreens.textCreatePassword"
    Then user scrolls to see element "onboardingHelpScreens.textCreateNumericPassWith6digits"
    Then user scrolls to see element "onboardingHelpScreens.textForYourSecurityWeWillPromptToYouAtSignInToTheApp"
    Then user scrolls to see element "onboardingHelpScreens.textTipsForCreatingYourPassword"
    Then user scrolls to see element "onboardingHelpScreens.textDoNotEnter3EqualOrConsecutiveDigits"
    Then user scrolls to see element "onboardingHelpScreens.textAvoidIncludePersonalData"
    Then user scrolls to see element "onboardingHelpScreens.textReadyYouCouldAlreadyRegisterAtBancoDelSol"
    Then user scrolls to see element "onboardingHelpScreens.textYouWillReceiveConfirmationEmailOnceYouFinishRegistration"
    Then user scrolls to see element "onboardingHelpScreens.textRegistrationSteps"
    Then user scrolls to see element "onboardingHelpScreens.carrCreatePassword"
    Then user scrolls to see element "onboardingHelpScreens.textBeginRegister"
    Then user scrolls to see element "HelpSection.carrLinkCellPhone"
    Then user scrolls and click on button or text "HelpSection.contactUs"
    Then user scrolls and click on button or text "onboardingHelpScreens.btnBack"
    Then user scrolls and click on button or text "HelpSection.chatButton"
    And user scrolls to see element "Chat.screenTitle"

    @regression_green @regression
    Scenario: Tap en opcion "No recibí el email de registro" durante onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    And user tap on "TopBar.helpButton"
    And user see text on screen "onboardingHelpScreens.textIDidNotReceiveRegistrationEmail"
    And user tap on "HelpSection.dontReceiveRegistrationEmail"
    And user see text on screen "onboardingHelpScreens.textGetAnEmailTolinkCell"

    @regression_green @regression
    Scenario: Tap en opción "Consejos para sacar tu foto" redirige a sección
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    And user tap on "TopBar.helpButton"
    Then user see text on screen "onboardingHelpScreens.textTipsToTakeYourSelfie"
    And user tap on "HelpSection.tipsForTakeSelphiePhoto"
    And user see text on screen "onboardingHelpScreens.textTakeSelfie"

    @regression_green @regression
    Scenario: Tap en opción "Cómo tomar la foto de mi DNI" redirige a sección
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    And user tap on "TopBar.helpButton"
    Then user see text on screen "onboardingHelpScreens.textHowToTakeDniPhoto"
    And user tap on "HelpSection.howTakeDniPhoto"
    Then user see text on screen "onboardingHelpScreens.textTakeDniPhoto"

    @regression_green @regression
    Scenario: Temas Sugeridos en la sección principal de Ayuda durante onboarding
    Given an user who is on "Welcome.registerButton"
    When user tap on "Welcome.registerButton"
    And user tap on "TopBar.helpButton"
    Then user see text on screen "onboardingHelpScreens.textIDidNotReceiveRegistrationEmail"
    And user tap on "HelpSection.dontReceiveRegistrationEmail"
    And user see text on screen "onboardingHelpScreens.textGetAnEmailTolinkCell"
    And user tap on "TopBar.closeModalButton"
    And user tap on "TopBar.helpButton"
    And user see text on screen "onboardingHelpScreens.textTipsToTakeYourSelfie"
    And user tap on "HelpSection.tipsForTakeSelphiePhoto"
    And user see text on screen "onboardingHelpScreens.textTakeSelfie"
    And user tap on "TopBar.closeModalButton"
    And user tap on "TopBar.helpButton"
    And user see text on screen "onboardingHelpScreens.textHowToTakeDniPhoto"
    And user tap on "HelpSection.howTakeDniPhoto"
    And user see text on screen "onboardingHelpScreens.textTakeDniPhoto"
    And user tap on "TopBar.closeModalButton"
    And user see text on screen "onboardingHelpScreens.textForRegistrationWeWillNeedYouToHaveYourCellPhoneCamerasAvailableAndHaveYourIDAtHand"